#! /bin/bash

# lockcmd="swaylock --screenshots --clock --indicator-idle-visible --indicator-radius 100 --indicator-thickness 7 --ignore-empty-password --ring-color 53E2AE --ring-ver-color 53E2AE --ring-wrong-color EE4F84 --key-hl-color EE4F84 --text-color ffffff --text-ver-color ffffff --text-wrong-color EE4F84 --line-color 00000000 --inside-color 00000088 --inside-ver-color 00000088 --inside-wrong-color 00000088 --separator-color 00000000 --fade-in 0.15 --effect-blur 10x2"
lockcmd="swaylock --screenshots --clock --indicator-idle-visible --indicator-radius 100 --indicator-thickness 7 --ignore-empty-password --ring-color 53E2AE --ring-ver-color 53E2AE --ring-wrong-color EE4F84 --key-hl-color EE4F84 --text-color ffffff --text-ver-color ffffff --text-wrong-color EE4F84 --line-color 00000000 --inside-color 00000088 --inside-ver-color 00000088 --inside-wrong-color 00000088 --separator-color 00000000 --fade-in 0.15 --effect-blur 10x2 -c 0B0A10ff"

# lockcmd="swaylockd --screenshots --indicator --clock --inside-wrong-color f38ba8 --ring-wrong-color 11111b --inside-clear-color a6e3a1 --ring-clear-color 11111b --inside-ver-color 89b4fa --ring-ver-color 11111b --text-color  f5c2e7 --indicator-radius 80 --indicator-thickness 5 --effect-blur 10x7 --effect-vignette 0.2:0.2 --ring-color 11111b --key-hl-color f5c2e7 --line-color 313244 --inside-color 0011111b --separator-color 00000000 --fade-in 0.1"

screenOff="sleep 5; hyprctl dispatch dpms off"
screenOn="hyprctl dispatch dpms on"

sway-audio-idle-inhibit & 
swayidle -w \
  timeout 1800 "$lockcmd & $screenOff" \
    resume "$screenOn"

###Here another config
# lockcmd2="pidof swaylock || swaylock --image ~/Pictures/tracks.jpg --clock --indicator --line-color cdd6f4ff --text-color cdd6f4ff --inside-color 1e1e2eff --ring-color 313244ff --line-ver-color cdd6f4ff --text-ver-color cdd6f4ff --inside-ver-color 1e1e2eff --ring-ver-color 313244ff --line-clear-color cdd6f4ff --text-clear-color cdd6f4ff --inside-clear-color 1e1e2eff --ring-clear-color 313244ff --line-clear-color cdd6f4ff --text-wrong-color 313244ff --inside-wrong-color f38ba8ff --ring-wrong-color 313244ff --key-hl-color cba6f7ff"
#
# swayidle -w timeout 900 $lockcmd2 before-sleep $lockcmd2 &
# swayidle -w timeout 450 'systemctl suspend'
###

# bat=$(ls /sys/class/power_supply | grep -m 1 "BAT")
#
# sway-audio-idle-inhibit & 
# swayidle -w \
#   timeout 1200 "$lockcmd & if [[ \"$(cat /sys/class/power_supply/$bat/status)\" == \"Discharging\" ]]; then systemctl suspend; else hyprctl dispatch dpms off; fi" resume "hyprctl dispatch dpms on"\
#     before-sleep "$lockcmd"
