#!/usr/bin/env bash

# bemenu theming
# . $HOME/.local/bin/bemenu-theming

# prompt="-p Clipboard:"

# cliphist list | head -80 | sed 's/^[0-9]*\s//' | bemenu -i $prompt | wl-copy

# Rofi Version
# NOTE: -p "Clipboard:" is not working
cliphist list | head -80 | sed 's/^[0-9]*\s//' | rofi -dmenu -i -p "Clipboard history:" | wl-copy
