#!/usr/bin/env bash

source $HOME/.config/hypr/dots/.scripts/variables

GOOGLE="https://www.google.com/search?q="
YANDEX="https://yandex.com/search/?text="
BRAVE="https://search.brave.com/search?q="
BING="https://www.bing.com/search?q="

google_search() {
    # Ask the user for a query
    query=$(rofi -dmenu -i -theme $LAUNCH1 -p "Google:" )

    # Exit if no query was entered
    [[ -z "$query" ]] && exit 1

    # Encode spaces as '+'
    encoded_query=$(echo "$query" | sed 's/ /+/g')

    # Open in default browser
    xdg-open "$GOOGLE$encoded_query"
}
yandex_search() {
    query=$(rofi -dmenu -i -p "Yandex:" -theme $LAUNCH2 )

    [[ -z "$query" ]] && exit 1

    encoded_query=$(echo "$query" | sed 's/ /+/g')

    xdg-open "$YANDEX$encoded_query"
}

brave_search() {
    query=$(rofi -dmenu -i -p "Brave:" -theme $LAUNCH4 )

    [[ -z "$query" ]] && exit 1

    encoded_query=$(echo "$query" | sed 's/ /+/g')

    xdg-open "$BRAVE$encoded_query"
}
bing_search() {
    query=$(rofi -dmenu -i -p "Bing:" -theme $LAUNCH3 )

    [[ -z "$query" ]] && exit 1

    encoded_query=$(echo "$query" | sed 's/ /+/g')

    xdg-open "$BING$encoded_query"
}

case "$1" in
google) google_search ;;
yandex) yandex_search ;;
brave) brave_search ;;
bing) bing_search ;;
esac
