#!/bin/sh

source $HOME/.config/hypr/dots/.scripts/utils/wallpaper/variables/vars
source $HOME/.config/hypr/dots/.scripts/variables

wallpaper_folder=$WALL_DIRECTORY

wallpaper_location="$(ls $wallpaper_folder | rofi -dmenu -p "Select a wallpaper" -theme $LAUNCHER_THEME)"


$set_env background "$wallpaper_folder/$wallpaper_location"

$wallpaper_scripts/wallpaper
