#!/bin/bash

export BEMENU_OPTS="
  -b\
  --tb '#AFAFAF'\
  --tf '#151515'\
  --fb '#151515'\
  --ff '#cac9dd'\
  --nb '#1d1f21'\
  --nf '#cac9dd'\
  --hb '#151515'\
  --hf '#75F3F4'\
  --nf '#cac9dd'\
  --af '#cac9dd'\
  --ab '#151515'\ 
  -H 32\ 
  -m 900\
  --fn 'SF Pro Rounded Regular 11'\
  --hp 8\
  --ch 16\
  --cw 2|
"
