#!/usr/bin/env bash

# bemenu theming
. $HOME/.local/bin/bemenu-theming

prompt="Path:"
root_path="$HOME"

find_path="$(find $root_path -maxdepth 3 -type d | \
             sed 's|^'$root_path/'||' | \
             bemenu -i --prompt="$prompt" "$@")"

if [[ ! -z "$find_path" ]]; then
   foot -D "$find_path"
fi

exit 0

