#!/bin/bash

source $HOME/.config/hypr/dots/.scripts/variables

sleep 7

zen-browser &

sleep 3

hyprctl dispatch $TYPEOFWORKSPACE $WORKSPACE2

foot --hold zellij a LostOnTheSeas &

sleep 2

hyprctl dispatch togglespecialworkspace notes

firefox &

sleep 2

hyprctl dispatch togglespecialworkspace notes
