#!/bin/bash

PROGRAM_NAME="waybar"

if pgrep "$PROGRAM_NAME"; then
  hyprctl keyword general:border_size 2
  hyprctl keyword general:gaps_in 1
  hyprctl keyword general:gaps_out 3
  hyprctl keyword decoration:rounding 0

elif [ $? -eq 1 ]; then
  hyprctl keyword general:border_size 2
  hyprctl keyword general:gaps_in 1
  hyprctl keyword general:gaps_out 3
  hyprctl keyword decoration:rounding 0
  "$PROGRAM_NAME" &

else
    echo "An error occurred while running grep."
fi
