#!/bin/bash

PROGRAM_NAME="waybar"

if pgrep "$PROGRAM_NAME"; then
  hyprctl keyword general:border_size 2
  hyprctl keyword general:gaps_in 1
  hyprctl keyword general:gaps_out 3
  hyprctl keyword decoration:rounding 0
  pkill -f "$PROGRAM_NAME"
  echo "'$PROGRAM_NAME' stop successfully!"

elif [ $? -eq 1 ]; then
  hyprctl keyword general:border_size 1
  hyprctl keyword general:gaps_in 6
  hyprctl keyword general:gaps_out 12
  hyprctl keyword decoration:rounding 9
  "$PROGRAM_NAME" &
  echo "'$PROGRAM_NAME' started successfully."

else
    echo "An error occurred while running grep."
fi
