#!/bin/bash
# Install yay to Aur
echo "######################################"
echo "####  1.  Enable the AUR helper   ####"
echo "######################################"
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si

echo "###############################################"
echo "#####   Installing Programming Languages  #####"
echo "###############################################"

# yay -S go ruby
yay -S  jdk-lts jdk-lts-doc 
###HERE
yay -S  google-java-format-git
yay -S  rustup
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

### JAVASCRIPT RELATED
yay -S  nodejs npm 
# yay -S  bun
# curl -fsSL https://bun.sh/install | bash

### PYTHON RELATED
yay -S  python-pip python-pipx

echo "#############################################"
echo "#####   Installation NVIM dependencies  #####"
echo "#############################################"

git clone https://github.com/lethc/hyprland-dotfiles.git ~/.config/hypr
git clone https://github.com/lethc/nvim-dotfiles.git ~/.config/nvim

#sudo npm install neovim
# npm install neovim
#sudo npm install -g npm@9.6.2
yay -S  python-black prettier prettierd stylua ripgrep fd gzip cliphist unzip deno composer yarn python-pynvim shfmt
yay -S  rar 
yay -S  xampp
# issues
# yay -S   #python-rpcq

echo "##############################"
echo "##  Installing ZSH plugins  ##"
echo "##############################" 

echo "Change shell root"
sudo usermod --shell /usr/bin/zsh root
echo "Change shell user"
sudo usermod --shell /usr/bin/zsh Lummyn

yay -S  zsh-syntax-highlighting zsh-autosuggestions lsd bat starship zsh-autocomplete-git zsh-sudo-git zsh-vi-mode-git

echo "########################################"
echo "##  Installing Hyprland dependencies  ##"
echo "########################################" 

yay -S  kitty hyprland-git xdg-desktop-portal-hyprland-git xdg-desktop-portal-gtk
yay -S  wofi dunst jq gojq-bin swayidle bc pamixer grim grimblast
yay -S  papirus-icon-theme playerctl 
yay -S  slurp socat swappy nm-connection-editor blueberry acpi 
yay -S  nwg-look-bin

# Adding plugins
hyprpm update
hyprpm add https://github.com/DreamMaoMao/hycov
hyprpm enable hycov

echo "#####################################"
echo "##  Installing Pacman Applications ##"
echo "#####################################"

yay -S fzf wget vdhcoapp-bin github-cli
yay -S  lsix nodejs-readability-cli selectdefaultapplication-git 
#yay -S megacmd
# yay -S ranger-git
yay -S   apple-fonts 
# yay -S   ttf-apple-emoji
###HERE
yay -S   rofi-lbonn-wayland-git
#yay -S   rofi-emoji
#issues with
yay -S  searxng-git 
yay -S  firefox-tridactyl firefox-tridactyl-native-bin speech-dispatcher
# yay -S  firefox-developer-edition 
yay -S  ncdu dust duf baobab iftop yazi smile code-minimap
yay -S  neovide-git
yay -S  whitesur-icon-theme-git whitesur-kvantum-theme-git whitesur-cursor-theme-git 
yay -S  texlive-latex biber texlive-binextra texlive-langspanish texlive-latexextra
 
# No eww anymore
#yay -S   eww-wayland 
yay -S  aylurs-gtk-shell
yay -S  bun-bin
yay -S  dart-sass
# yay -S  inotify-tools
yay -S  waybar
yay -S  swaync
yay -S  wf-recorder 
yay -S  swaylock-effects-git sway-audio-idle-inhibit-git 
yay -S  wl-clip-persist-git
yay -S  wayshot
yay -S  cliphist hyprpicker-git
yay -S  swww
yay -S  vimv
yay -S  gcolor3

echo "######################################"
echo "###### Installing frequent apps ######"
echo "######################################"
yay -S  foot-git foot-terminfo-git zoxide bemenu-wayland
yay -S  gtt-bin youtube-tui-git 
yay -S  w3m lynx httrack 
yay -S  vlc obsidian 
yay -S  tori-bin python-pytube 
yay -S  sioyek amberol anki-bin kooha
yay -S  resources
yay -S  morgen-bin
pipx install wisdom-tree

# Install nice clipboard manager
# https://github.com/savedra1/clipse?tab=readme-ov-file#installation
go install github.com/savedra1/clipse@v0.0.6 

# cargo install bard-rs

echo "########################################"
echo "############ SDDM Theme  ###############"
echo "########################################" 
yay -S  sddm qt5-graphicaleffects qt5-svg qt5-quickcontrols2 nsxiv imv
# yay -S  sddm-theme-corners-git

echo "creating sddm.conf.d"
sudo mkdir /etc/sddm.conf.d/

echo "creating sddm.conf.d/config"
touch config ~/Desktop/config
echo "[Theme]" > ~/Desktop/config 
echo "Current=corners" >> ~/Desktop/config
sudo mv ~/Desktop/config /etc/sddm.conf.d/

echo "setting theme"
sudo sed -i 's/    passwordMaskDelay: 1000$/    passwordMaskDelay: 0/' /usr/share/sddm/themes/corners/components/PasswordPanel.qml
echo "theme setted correctly"

echo "Installing FZF"
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install

echo "######################################"
echo "#####   Installation completed   #####"
echo "######################################"
