#!/bin/bash

echo "######################################"
echo "####  1.  Important Packags       ####"
echo "######################################"

mkdir ~/Home
mkdir ~/Documents/Library
mkdir ~/.local/bin
mkdir ~/Downloads/Git
sleep 2
cd ~/Downloads/Git

# ASKN
sudo pacman -S foot foot-terminfo cliphist wl-clip-persist rofi-wayland hyprpaper kitty waybar swaync zoxide lsd bat swww
sudo pacman -S ttf-firacode-nerd ttf-nerd-fonts-symbols ttf-victor-mono-nerd 

# ASK
git clone https://aur.archlinux.org/yay-bin.git ~/Downloads/Git/yay-bin/
cd  ~/Downloads/Git/yay-bin
makepkg -si

yay -S  zsh-syntax-highlighting zsh-autosuggestions zsh-completions zsh-autocomplete-git zsh-sudo-git zsh-vi-mode-git
yay -S clipse-bin clipse-gui blueberry-wayland
# When choosing Color scheme: it gotta be Breeze Dark (KColorScheme) to work Properly
yay -S qt6ct-kde
#yay -S qt5ct-kde 

# If Open with in Dolphin still doesn't work
# ln -s /etc/xdg/menus/plasma-applications.menu /etc/xdg/menus/applications.menu
# kbuildsycoca6 --noincremental

ln -sf "${HOME}/.config/hypr/dots/.p10k.zsh" "${HOME}/"
echo "p10k linked"
ln -sf "${HOME}/.config/hypr/dots/rofi" "${HOME}/.config"
echo "rofi linked"
ln -sf "${HOME}/.config/hypr/dots/television" "${HOME}/.config"
echo "television linked"
ln -sf "${HOME}/.config/hypr/dots/tridactyl" "${HOME}/.config"
echo "tridactyl linked"
ln -sf "${HOME}/.config/hypr/dots/zellij" "${HOME}/.config"
echo "zellij linked"
ln -sf "${HOME}/.config/hypr/dots/gitui" "${HOME}/.config"
echo "gitui linked"
ln -sf "${HOME}/.config/hypr/dots/qutebrowser" "${HOME}/.config"
echo "Qutebrowser linked"
ln -sf "${HOME}/.config/hypr/dots/zathura" "${HOME}/.config"
echo "zathura linked"
ln -sf "${HOME}/.config/hypr/dots/mpv" "${HOME}/.config"
echo "mpv linked"
ln -sf "${HOME}/.config/hypr/dots/foot" "${HOME}/.config"
echo "foot linked"
ln -sf "${HOME}/.config/hypr/dots/ghostty" "${HOME}/.config"
echo "ghostty linked"
ln -sf "${HOME}/.config/hypr/dots/kitty" "${HOME}/.config"
echo "kitty linked"
ln -sf "${HOME}/.config/hypr/dots/waybar" "${HOME}/.config"
echo "Waybar linked"
ln -sf "${HOME}/.config/hypr/dots/swaync" "${HOME}/.config"
echo "swaync linked"
ln -sf "${HOME}/.config/hypr/dots/.scripts" "${HOME}"
echo ".scripts linked"
ln -sf "${HOME}/.config/hypr/dots/.gitignore" "${HOME}"
echo ".gitignore linked"
ln -sf "${HOME}/.config/hypr/dots/.gitconfig" "${HOME}"
echo ".gitconfig linked"
ln -sf "${HOME}/.config/hypr/dots/.inputrc" "${HOME}"
echo ".inputrc linked"
#ln -sf "${HOME}/.config/hypr/dots/fcitx5" "${HOME}/.config"
#echo "fcitx5 linked"
ln -sf "${HOME}/.config/hypr/dots/.zshrc" "${HOME}"
echo ".zshrc linked"
ln -sf "${HOME}/.config/hypr/dots/xdg-desktop-portal" "${HOME}/.config"
echo "xdg-desktop-portal config linked"
ln -sf "${HOME}/.config/hypr/dots/mimeapps.list" "${HOME}/.config"
echo "mimeapps linked"

echo "CURSOR QT APPLICATIONS"
mkdir -p "${HOME}/.icons/default"
touch "${HOME}/.icons/default/index.theme"
echo "qt cursor config created"

ln -sf "${HOME}/.config/hypr/dots/.scripts/utils/linkhandler" "${HOME}/.local/bin/"
echo "linkhandler mpv newsboat linked"
ln -sf "${HOME}/.config/hypr/dots/newsboat" "${HOME}/.config"
echo "Newsboat linked"
ln -sf "${HOME}/.config/hypr/dots/.scripts/zellijs/fzj" "${HOME}/.local/bin/"
echo "FZJ linked"
ln -sf "${HOME}/.config/hypr/dots/bat" "${HOME}/.config"
echo "bat theme"
ln -sf "${HOME}/.config/hypr/dots/bookmenu/" "${HOME}/.config"
echo "Bookmenu configuration linked"
#echo "INSERT PASSWORD FOR LINK SCRIPTS"
#sudo ln -sf "${HOME}/.config/hypr/dots/dunst/scripts/notification-sound" /usr/bin/
#echo "notification-sound linked"
# Force electron applications to use Wayland with the following files
ln -sf "${HOME}/.config/hypr/dots/electron-flags.conf" "${HOME}/.config"
ln -sf "${HOME}/.config/hypr/dots/code-flags.conf" "${HOME}/.config"
ln -sf "${HOME}/.config/hypr/dots/freetube.desktop" "${HOME}/.local/share/applications/"


echo "########################################"
echo "############ SDDM Theme  ###############"
echo "########################################" 

sudo cp -r "${HOME}/.config/hypr/dots/sddm-theme/corners" /usr/share/sddm/themes
sudo cp -r "${HOME}/.config/hypr/dots/sddm-theme/silent" /usr/share/sddm/themes
echo "SDDM themes linked"
sudo ln -sf "${HOME}/.config/hypr/dots/.scripts/zellijs/zs" "/usr/bin/"
echo "zs linked"

# ASKN
yay -S  sddm qt5-graphicaleffects qt5-svg qt5-quickcontrols2

echo "creating sddm.conf.d"
sudo mkdir /etc/sddm.conf.d/

echo "creating sddm.conf.d/config"
touch config ~/Desktop/config
# Set corner theme as default
# echo "[Theme]" > ~/Desktop/config 
# echo "Current=corners" >> ~/Desktop/config
# Set silent theme as default
echo "[General]" > ~/Desktop/config 
echo "GreeterEnvironment=QML2_IMPORT_PATH=/usr/share/sddm/themes/silent/components/,QT_IM_MODULE=qtvirtualkeyboard" >> ~/Desktop/config
echo "[Theme]" >> ~/Desktop/config 
echo "Current=silent" >> ~/Desktop/config
sudo mv ~/Desktop/config /etc/sddm.conf.d/

echo "theme setted correctly"

echo "##############################"
echo "##  Installing ZSH plugins  ##"
echo "##############################" 

echo "Change shell root"
sudo usermod --shell /usr/bin/zsh root
echo "Change shell user"
sudo usermod --shell /usr/bin/zsh $user

echo "########################################"
echo "##  Installing Hyprland dependencies  ##"
echo "########################################" 

# Adding plugins
hyprpm update
hyprpm add https://github.com/hyprwm/hyprland-plugins
hyprpm enable hyprbars
hyprpm update
hyprpm reload -n

# ASKN
# INSTALLED IN ARCHLINUX-INSTALLER
# yay -S  hyprland cpio meson cmake hyprland-qtutils xdg-desktop-portal-hyprland xdg-desktop-portal-gtk hyprlock hypridle hyprpicker

# JQ is really important for my scripts
yay -S  jq pamixer nm-connection-editor acpi nwg-look nwg-displays grim slurp

# SCREENSHOT script: grim slurp
# ASK
yay -S grimblast

# ARE YOU REQUIRED?
yay -S gojq-bin bc playerctl socat swappy speech-dispatcher gcolor3 nsxiv imv  apple-fonts hyprshot wf-recorder  python-pytube 

echo "######################################"
echo "###### Installing frequent apps ######"
echo "######################################"

# INSTALLING RUST
# ASKN
yay -S  rustup
# Install rustc compiler
rustup install stable
# Install rust-analyzer (nvim LSP)
yay -S rust-analyzer


# Installing fonts
sudo ln -sf "${HOME}/.config/hypr/dots/conf.avail/" /etc/fonts/
sudo ln -sf /etc/fonts/conf.avail/75-joypixels.conf /etc/fonts/conf.d/

# ASKN
yay -S wget github-cli lsix firefox-tridactyl ncdu dust duf baobab iftop yazi
yay -S ueberzugpp xournalpp obsidian kooha resources tgpt

# ASK
yay -S nodejs-readability-cli firefox-tridactyl-native-bin smile  ttf-joypixels 
#ttf-misans
yay -S ttf-ms-win11-auto
# ttf-maple Doesn't exist anymore
yay -S ttf-maplemono
yay -S  gtt-bin tori-bin anki-bin zen-browser-bin freetube-bin curd vivaldi google-chrome
yay -S bun-bin vimv
yay -S megasync-bin
yay -S input-remapper-bin
yay -S hyprsunset

# pipx install wisdom-tree

# yay -S youtube-local
# yay -S  sioyek 
# yay -S  amberol
# yay -S  morgen-bin
# yay -S pcloud-drive

# AND YOU
# yay -S vdhcoapp-bin
# yay -S selectdefaultapplication-git 
# yay -S megacmd

#issues with
#yay -S  searxng-git 
# yay -S  firefox-developer-edition 


# WAYBAR Vertical modules
# ASKN
#yay -S pacman-contrib
#yay -S power-profile
# ASK
#yay -S aurutils-git wttrbar hyprshade 
# yay -S wl-screenrec

ln -sf "${HOME}/.config/hypr/dots/yazi" "${HOME}/.config"
echo "yazi linked"

# Install Yazi plugins
ya pack -a yazi-rs/plugins:smart-enter
ya pack -a josephschmitt/auto-layout

# LaTeX packages
# yay -S  texlive-latex biber texlive-binextra texlive-langspanish texlive-latexextra

echo "#############################################"
echo "#####   Installation  THEMES            #####"
echo "#############################################"

#mkdir "${HOME}/.themes"
#cp -r "${HOME}/.config/hypr/dots/gtk/Everforest-Dark-BL" "${HOME}/.themes"
#cp -r "${HOME}/.config/hypr/dots/gtk/Orchis-Yellow-Dark" "${HOME}/.themes"
#echo "GTK3 theme copied"

## DOWNLOAD GTK THEMES
# WhiteSur Theme
git clone https://github.com/vinceliuice/WhiteSur-gtk-theme.git --depth=1 ~/Downloads/Git/WhiteSur-gtk-theme
cd "${HOME}/Downloads/Git/WhiteSur-gtk-theme"
./install.sh
# For gtk4
./install.sh -l

# Orchis Theme
git clone https://github.com/vinceliuice/Orchis-theme.git ~/Downloads/Git/Orchis-theme
cd "${HOME}/Downloads/Git/Orchis-theme"
./install.sh
./install.sh -l

# Win11 Theme
git clone https://github.com/yeyushengfan258/Win11-gtk-theme.git ~/Downloads/Git/Win11-gtk-theme
cd "${HOME}/Downloads/Git/Win11-gtk-theme"
./install.sh --tweaks round
./install.sh --tweaks round -l

# Download Material-GTK-Themes
git clone https://github.com/Fausto-Korpsvart/Material-GTK-Themes.git ~/Downloads/Git/Material-GTK-Themes
cd "${HOME}/Downloads/Git/Material-GTK-Themes/themes"
./install.sh -t red -l 

## DOWNLOAD ICON THEMES
# WhiteSur Icon Theme
git clone https://github.com/vinceliuice/WhiteSur-icon-theme.git --depth=1 ~/Downloads/Git/WhiteSur-icon-theme
cd "${HOME}/Downloads/Git/WhiteSur-icon-theme"
./install.sh

# Reversal Icon Theme
git clone https://github.com/yeyushengfan258/Reversal-icon-theme.git ~/Downloads/Git/Reversal-icon-theme
cd "${HOME}/Downloads/Git/Reversal-icon-theme"
./install.sh

# Win11 Icon Theme
# git clone https://github.com/yeyushengfan258/Win11-icon-theme.git ~/Downloads/Git/Win11-icon-theme
# cd "${HOME}/Downloads/Git/Win11-icon-theme"
# ./install.sh

git clone https://github.com/mjkim0727/Eleven-icon-theme.git ~/Downloads/Git/Eleven-icon-theme
cd "${HOME}/Downloads/Git/Eleven-icon-theme"
./install.sh

# Zephyr Icon Theme
git clone https://github.com/Rudraksh88/zephyr-icons.git ~/.local/share/icons/Zephyr

# KVANTUM THEME FOR QT APPS
ln -sf "${HOME}/.config/hypr/dots/Kvantum" "${HOME}/.config"

## DOWNLOAD KDE THEMES
# Download Orchis Theme
git clone https://github.com/vinceliuice/Orchis-kde.git

# Download Zephyr Kvantum Theme
git clone https://github.com/Rudraksh88/zephyr-kvantum.git ~/Downloads/Git/Zephyr

# Download Macquoia Theme
# git clone https://github.com/vinceliuice/MacSequoia-kde.git ~/Downloads/Git/MacSequoia-kde

# Download Whitesur Theme
# git clone https://github.com/vinceliuice/WhiteSur-kde.git ~/Downloads/Git/WhiteSur-kde

# Download Win11 Theme
git clone https://github.com/yeyushengfan258/Win11OS-kde.git ~/Downloads/Git/Win11OS-kde

# DISABLING RIGHT TOP BUTTONS IN GTK-4 APPS

yay -S dconf-editor

# Go to  org > gnome > desktop > wm > preferences > button-layout
# AND  Under "custom value" remove everything except for "appmenu" -> 'icon:'

echo "#############################################"
echo "#####   Installation NVIM dependencies  #####"
echo "#############################################"

# ASK
yay -S dotnet-sdk jdk-lts jdk-lts-doc go
# yay -S go ruby
###HERE
# yay -S  google-java-format-git

### JAVASCRIPT RELATED
# ASKN
yay -S  nodejs npm 
# yay -S  bun
# curl -fsSL https://bun.sh/install | bash

### PYTHON RELATED
# ASKN
yay -S  python-pip python-pipx

### LUA RELATED
# ASKN
yay -S  lua51 luarocks

# Download hypr in ~/.config/hypr before enter here
#git clone https://github.com/lethc/hyprland-dotfiles.git ~/.config/hypr
git clone https://github.com/lethc/nvim-dotfiles.git ~/.config/nvim

#sudo npm install neovim
# npm install neovim
#sudo npm install -g npm@9.6.2
# ASK
yay -S  shell-color-scripts-git hub prettierd rar
yay -S code-minimap-bin
# ASKN
yay -S  python-black prettier stylua ripgrep 
yay -S  fd gzip unzip deno 
yay -S  composer python-pynvim shfmt
yay -S  yarn 
# yay -S   #python-rpcq

# Python Debug in neovim
mkdir -p ~/env/.virtualenvs
cd ~/env/.virtualenvs
python -m venv debugpy
debugpy/bin/python -m pip install debugpy
# Rust, C and C++ debuger
yay -S codelldb-bin
yay -S thunderbird thunderbird-i18n-en-gb todoist-appimage morgen-bin

 
echo "######################################"
echo "#####   Installation completed   #####"
echo "######################################"
