#!/bin/bash
echo "######################################"
echo "#######   Clonning repos  ############"
echo "######################################"

mkdir ~/Home
mkdir ~/Documents/Library
git clone https://git.sr.ht/~heckyel/yt-local ~/env/yt-local
# cp "${HOME}/.config/hypr/dots/.scripts/.megabot" ~/Sync/

# Python Debug in neovim
mkdir ~/env/.virtualenvs
cd ~/env/.virtualenvs
python -m venv debugpy
debugpy/bin/python -m pip install debugpy
# Rust, C and C++ debuger
yay -S codelldb

echo "###################################"
echo "########  Create Symlinks  ########"
echo "###################################"

# ln -sf "${HOME}/.config/hypr/dots/ags" "${HOME}/.config"
# echo "Ags linked"

ln -sf "${HOME}/.config/hypr/dots/foot" "${HOME}/.config"
echo "foot linked"

ln -sf "${HOME}/.config/hypr/dots/kitty" "${HOME}/.config"
echo "kitty linked"

ln -sf "${HOME}/.config/hypr/dots/gitui" "${HOME}/.config"
echo "Gitui linked"

ln -sf "${HOME}/.config/hypr/dots/mpv" "${HOME}/.config"
echo "mpv linked"

ln -sf "${HOME}/.config/hypr/dots/newsboat" "${HOME}/.config"
echo "newsboat linked"

# rm -r ~/.config/qutebrowser/
ln -sf "${HOME}/.config/hypr/dots/qutebrowser" "${HOME}/.config"
echo "qutebrowser linked"

ln -sf "${HOME}/.config/hypr/dots/zathura" "${HOME}/.config"
echo "zathura linked"

ln -sf "${HOME}/.config/hypr/dots/sioyek" "${HOME}/.config"
echo "sioyek linked"

ln -sf "${HOME}/.config/hypr/dots/zellij" "${HOME}/.config"
echo "zellij linked"

# rm -r ~/.config/gtk-4.0/
ln -sf "${HOME}/.config/hypr/dots/gtk/gtk-4.0" "${HOME}/.config"
echo "GTK4 theme linked"


ln -sf "${HOME}/.config/hypr/dots/" "${HOME}/.config"
kvantummanager --set Orchis-dark
# Change the QT themes with an application like qt5ct or qt6ct
echo "Kvantum theme linked"

ln -sf "${HOME}/.config/hypr/dots/.zshrc" "${HOME}"
echo ".zshrc linked"

ln -sf "${HOME}/.config/hypr/dots/.gitignore" "${HOME}"
echo ".gitignore linked"

ln -sf "${HOME}/.config/hypr/dots/.gitconfig" "${HOME}"
echo ".gitconfig linked"

ln -sf "${HOME}/.config/hypr/dots/.inputrc" "${HOME}"
echo ".inputrc linked"

ln -sf "${HOME}/.config/hypr/dots/fcitx5" "${HOME}/.config"
echo "fcitx5 linked"

ln -sf "${HOME}/.config/hypr/dots/.scripts" "${HOME}"
echo ".scripts linked"

ln -sf "${HOME}/.config/hypr/dots/tridactyl" "${HOME}/.config"
echo "tridactyl linked"

ln -sf "${HOME}/.config/hypr/dots/imv" "${HOME}/.config"
echo "imv linked"

ln -sf "${HOME}/.config/hypr/dots/yazi" "${HOME}/.config"
echo "yazi linked"

mkdir ~/.local/bin
ln -sf "${HOME}/.config/hypr/dots/.scripts/linkhandler" "${HOME}/.local/bin/"
echo "linkhandler mpv newsboat linked"

ln -sf "${HOME}/.config/hypr/dots/mimeapps.list" "${HOME}/.config"
echo "mimeapps linked"

echo "cursor qt applications"
mkdir -p "${HOME}/.icons/default"
touch "${HOME}/.icons/default/index.theme"
echo "qt cursor config created"

ln -sf "${HOME}/.config/hypr/dots/.scripts/fzf-zellij/fzj" "${HOME}/.local/bin/"
echo "FZJ linked"

ln -sf "${HOME}/.config/hypr/dots/bat" "${HOME}/.config"
echo "bat theme"

echo "Insert password for link scripts"

sudo ln -sf "${HOME}/.config/hypr/dots/dunst/scripts/notification-sound" /usr/bin/
echo "notification-sound linked"

sudo cp -r "${HOME}/.config/hypr/dots/sddm-theme/corners" /usr/share/sddm/themes
echo "SDDM theme linked"

sudo ln -sf "${HOME}/.config/hypr/dots/bookmenu/bookmenu" /usr/bin/
echo "Bookmenu linked"

sudo ln -sf "${HOME}/.config/hypr/dots/bookmenu/documentation/bookmenu.1" /usr/share/man/man1
echo "Bookmenu manual linked"

ln -sf "${HOME}/.config/hypr/dots/bookmenu/config/bookmenu/" "${HOME}/.config"
echo "Bookmenu configuration linked"

ln -sf "${HOME}/.config/hypr/dots/.scripts/bemenu-theming" "${HOME}/.local/bin/"
echo "Bemenu Theme linked"

ln -sf "${HOME}/.config/hypr/dots/xdg-desktop-portal" "${HOME}/.config"
echo "xdg-desktop-portal config linked"

ln -sf "${HOME}/.config/hypr/dots/rofi" "${HOME}/.config"
echo "rofi linked"

echo "Changing papirus Icon Colour"

yay -S papirus-folders-git
papirus-folders -C grey

echo "theme completed"

mkdir "${HOME}/.themes"
cp -r "${HOME}/.config/hypr/dots/gtk/Everforest-Dark-BL" "${HOME}/.themes"
cp -r "${HOME}/.config/hypr/dots/gtk/Orchis-Yellow-Dark" "${HOME}/.themes"
echo "GTK3 theme copied"

# Make fonts work without google-noto-fonts
# https://codeberg.org/dnkl/foot/wiki#user-content-how-do-i-get-colored-emojis
ln -sf "${HOME}/.config/hypr/dots/conf.avail/" /etc/fonts/
ln -sf /etc/fonts/conf.avail/75-joypixels.conf /etc/fonts/conf.d/

ln -sf "${HOME}/.config/hypr/dots/waybar" "${HOME}/.config"
echo "Waybar linked"

ln -sf "${HOME}/.config/hypr/dots/swaync" "${HOME}/.config"
echo "swaync linked"

git clone https://github.com/vinceliuice/WhiteSur-gtk-theme.git --depth=1 ~/Git/WhiteSur-gtk-theme
cd "${HOME}/Git/WhiteSur-gtk-theme"

./install.sh
# For gtk4
./install.sh -l

git clone https://github.com/vinceliuice/WhiteSur-icon-theme.git --depth=1 ~/Git/WhiteSur-icon-theme
cd "${HOME}/Git/WhiteSur-icon-theme"

# For qt applications
git clone https://github.com/vinceliuice/MacSequoia-kde ~/Git

./install.sh

# Force electron applications to use Wayland with the following files

ln -sf "${HOME}/.config/hypr/dots/electron-flags.conf" "${HOME}/.config"
ln -sf "${HOME}/.config/hypr/dots/code-flags.conf" "${HOME}/.config"

# DISABLING right buttons in gtk-4 applications

# Download 

yay -S dconf-editor 

# Go to  org > gnome > desktop > wm > preferences > button-layout 

# AND  Under "custom value" remove everything except for "appmenu" -> 'icon:'


# --------------------------------------------------------------------------------

#ln -sf "${HOME}/.config/hypr/dots/dunst" "${HOME}/.config"
#echo "dunst linked"

#rm -r ~/.config/ranger/
#ln -sf "${HOME}/.config/hypr/dots/ranger" "${HOME}/.config"
#echo "ranger linked"

#ln -sf "${HOME}/.config/hypr/dots/wofi" "${HOME}/.config"
#echo "wofi linked"

# ln -sf "${HOME}/.config/hypr/dots/md2anki" "${HOME}/.config"
# echo "md2anki linked"

# echo "ICONS" | sleep 2
# cd /tmp/
# git clone https://github.com/4e6anenk0/Rowaita-icon-theme.git
# cd Rowaita-icon-theme
# cp -r Rowaita-Ubuntu-Dark/ ~/.icons/
