# Catppuccin Mocha Colors:
# Background: #1e1e2e
# Surface: #313244
# Text: #cdd6f4
# Subtext: #a6adc8
# Blue: #89b4fa
# Pink: #f5c2e7
# Red: #f38ba8
# Green: #a6e3a1
# Teal: #94e2d5
# Peach: #fab387
# Yellow: #f9e2af
# Mauve: #cba6f7
# Flamingo: #f2cdcd
# Rosewater: #f5e0dc

set -g status-style bg=#1e1e2e

# Copy/select mode
set -g mode-style "bg=#89b4fa,fg=#1e1e2e"

# Pane borders
set -g pane-border-style fg=#313244
set -g pane-active-border-style fg=#89b4fa

# Left status
set -g status-left "#[bg=#f38ba8,fg=#1e1e2e] #S #[bg=#1e1e2e,fg=#f38ba8,nobold,noitalics,nounderscore]"
set -g status-left-length 30

# Right status
set -g status-right "#[bg=#1e1e2e,fg=#a6e3a1] #[bg=#94e2d5,fg=#1e1e2e] %A %d %B - %H:%M "

# Active window
set -wg window-status-current-format "#[bg=#1e1e2e,fg=#89b4fa,nobold,noitalics,nounderscore] #[bg=#89b4fa,fg=#1e1e2e,bold] #{window_name}#{?window_zoomed_flag,*Z,} #[bg=#1e1e2e,fg=#89b4fa,nobold,noitalics,nounderscore]"

# Inactive windows
set -wg window-status-format "#[bg=#1e1e2e,fg=#1e1e2e,noitalics] #[bg=#1e1e2e,fg=#a6adc8] #{window_name} #[bg=#1e1e2e,fg=#1e1e2e,noitalics]"
