# -------------------------
# STATUS BAR (rosewood style)
# -------------------------
set -g status-position bottom
set -g status-bg '#11080D'
set -g status-fg '#D0CDC8'

set -g status-left '#[fg=#EA8476] #S '
set -g status-right '#[fg=#BC6C97]%H:%M #[fg=#95A682]%d-%b'

setw -g window-status-current-style fg=#11080D,bg=#BC6C97
setw -g window-status-style fg=#534E46,bg=#11080D

# -------------------------
# BORDERS
# -------------------------
set -g pane-border-style fg='#534E46'
set -g pane-active-border-style fg='#A68295'
