# rose_fg="#D0CDC8"
# rose_muted="#534E46"
# rose_green="#95A682"
# rose_pink="#BC6C97"
# rose_red="#d65a6f"
# rose_coral="#EA8476"
# rose_active="#A68295"
# rose_bg="#11080D"

# -------------------------
# STATUS BAR (light rosewood adapted)
# -------------------------
# OneDark tmux theme (blue active tab variant)

set -g status-style bg=#282c34

# Copy/select mode
set -g mode-style "bg=#61afef,fg=#282c34"

# Pane borders
set -g pane-border-style fg=#3e4452
set -g pane-active-border-style fg=#61afef

# Left status
set -g status-left "#[bg=#e06c75,fg=#282c34] #S #[bg=#282c34,fg=#e06c75,nobold,noitalics,nounderscore]"
set -g status-left-length 30

# Right status
set -g status-right "#[bg=#282c34,fg=#98c379] #[bg=#56b6c2,fg=#282c34] %A %d %B - %H:%M "

# Active window (blue instead of purple)
set -wg window-status-current-format "#[bg=#282c34,fg=#61afef,nobold,noitalics,nounderscore] #[bg=#61afef,fg=#282c34,bold] #{window_name}#{?window_zoomed_flag,*Z,} #[bg=#282c34,fg=#61afef,nobold,noitalics,nounderscore]"

# Inactive windows
set -wg window-status-format "#[bg=#282c34,fg=#282c34,noitalics] #[bg=#282c34,fg=#5c6370] #{window_name} #[bg=#282c34,fg=#282c34,noitalics]"
