# rose_bg="#F6ECEF"
# rose_fg="#4E4348"
# rose_muted="#9A8E93"
# rose_green="#95A682"
# rose_pink="#BC6C97"
# rose_coral="#EA8476"
# rose_active="#C9A8BB"
# rose_red="#D84A3D"

# -------------------------
# STATUS BAR (light rosewood)
# -------------------------
set -g status-style bg=#FAFAFA
# avoid invisible color to select text in select mode
# set -g mode-style "bg=#FAFAFA,fg=#383A42"
set -g mode-style "bg=#C9A8BB,fg=#383A42"

set -g pane-border-style fg=#DCD7CF
set -g pane-active-border-style fg=#A68295

set -g status-left "#[bg=#EA8476,fg=#FAFAFA] #S #[bg=#FAFAFA,fg=#EA8476,nobold,noitalics,nounderscore]"

set -g status-right "#[bg=#FAFAFA,fg=#95A682] #[bg=#BC6C97,fg=#FAFAFA] %A %d %B - %H:%M "

set -wg window-status-current-format "#[bg=#FAFAFA,fg=#BC6C97,nobold,noitalics,nounderscore] #[bg=#BC6C97,fg=#FAFAFA] #{window_name}#{?window_zoomed_flag,*Z,} #[bg=#FAFAFA,fg=#BC6C97,nobold,noitalics,nounderscore]"

set -wg window-status-format "#[bg=#FAFAFA,fg=#FAFAFA,noitalics] #[bg=#FAFAFA,fg=#8A847C] #{window_name} #[bg=#FAFAFA,fg=#FAFAFA,noitalics]"
