# -------------------------
# STATUS BAR (light rosewood style)
# -------------------------
set -g status-position bottom
set -g status-bg '#FAFAFA'
set -g status-fg '#54555B'

set -g status-left '#[fg=#FF75A0] #S '
set -g status-right '#[fg=#D84A3D]%H:%M #[fg=#50A14F]%d-%b'

setw -g window-status-current-style fg=#FAFAFA,bg=#4078F2
setw -g window-status-style fg=#54555B,bg=#FAFAFA

# -------------------------
# BORDERS
# -------------------------
set -g pane-border-style fg='#C18401'
set -g pane-active-border-style fg='#4078F2'
