# OneDark Pro Colors:
# Background: #282c34
# Surface: #353b45
# Text: #abb2bf
# Subtext: #5c6370
# Blue: #61afef
# Purple: #c678dd
# Red: #e06c75
# Green: #98c379
# Teal: #56b6c2
# Orange: #d19a66
# Yellow: #e5c07b
# Cyan: #56b6c2

set -g status-style bg=#282c34

# Copy/select mode
set -g mode-style "bg=#61afef,fg=#282c34"

# Pane borders
set -g pane-border-style fg=#353b45
set -g pane-active-border-style fg=#61afef

# Left status
set -g status-left "#[bg=#e06c75,fg=#282c34] #S #[bg=#282c34,fg=#e06c75,nobold,noitalics,nounderscore]"
set -g status-left-length 30

# Right status
set -g status-right "#[bg=#282c34,fg=#98c379] #[bg=#56b6c2,fg=#282c34] %A %d %B - %H:%M "

# Active window
set -wg window-status-current-format "#[bg=#282c34,fg=#61afef,nobold,noitalics,nounderscore] #[bg=#61afef,fg=#282c34,bold] #{window_name}#{?window_zoomed_flag,*Z,} #[bg=#282c34,fg=#61afef,nobold,noitalics,nounderscore]"

# Inactive windows
set -wg window-status-format "#[bg=#282c34,fg=#282c34,noitalics] #[bg=#282c34,fg=#5c6370] #{window_name} #[bg=#282c34,fg=#282c34,noitalics]"
