scroll_offset = 6

use_trash = false
watch_files = false
xdg_open = false
xdg_open_fork = true

[display]
# default, vsplit
mode = "default"

automatically_count_files = false
collapse_preview = true
column_ratio = [1, 4, 4]
# line_number_style = "absolute"
show_borders = true
show_hidden = false
show_icons = true 
tilde_in_titlebar = true

[display.sort]
case_sensitive = false
directories_first = true
reverse = false
method = "natural" 	# lexical, mtime, natural

[preview]
max_preview_size = 2097152 # 2MB
# preview_script = "~/.config/joshuto/preview_file.sh"
preview_shown_hook_script = "~/.config/joshuto/on_preview_shown.sh"
preview_removed_hook_script = "~/.config/joshuto/on_preview_removed.sh"

[tab]
# inherit, home, root
home_page = "inherit"
