# Shell
shell zsh

# BEGIN_KITTY_THEME
include kitty-theme.conf
# END_KITTY_THEME

# Font
# font_family     HackNerdFont
# font_family      JetBrainsMono Nerd Font
# font_family      RobotoMono Nerd Font 
# font_family      Illinois Mono
# font_family VictorMono Nerd Font, Noto Color Emoji
# bold_font Fira Code Nerd Font
# italic_font VictorMono Nerd Font
# bold_italic_font Maple Mono NF
# bold_font_style Bold
# italic_font_style Bold Italic
# bold_italic_font_style Bold Italic

font_family      Maple Mono NF CN
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 11

# Nerd Font fallback
# symbol_map U+E000-U+F8FF Symbols Nerd Font

# Font rendering
# modify_font cell_height 115%
modify_font cell_height 125%
# modify_font underline_position 2
# modify_font underline_thickness 100%

# Window padding
window_padding_width 5

# Cursor
cursor_shape beam
cursor_beam_thickness 1.8

# Scrollback
# scrollback_lines 10000
# wheel_scroll_multiplier 53.0
scrollback_lines 10000
wheel_scroll_multiplier 5

# Window
remember_window_size yes
initial_window_width 700
initial_window_height 500

# Title
dynamic_background_opacity yes
background_opacity 0.95
# background_image ~/Pictures/Republic/img-5.jpg
# background_image_layout scaled
# background_image_linear yes
# background_tint 0.93


# Mouse
# mouse_hide_wait 0.0
mouse_hide_wait 3.0

# URL handling
detect_urls yes
url_color #61afef
url_style curly

# Keybindings
# Clipboard
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

# Font size
map ctrl+plus change_font_size all +1.0
map ctrl+minus change_font_size all -1.0
map ctrl+0 change_font_size all 0

# Search
# map ctrl+shift+f show_scrollback

# Scrollback
map ctrl+shift+k scroll_line_up
map ctrl+shift+j scroll_line_down
map ctrl+shift+l scroll_page_up
map ctrl+shift+h scroll_page_down


# URL hints
map ctrl+m kitten hints --type url
map ctrl+shift+m kitten hints --type url --program -

# map ctrl+alt+h neighboring_window left
# map ctrl+alt+l neighboring_window right
# map ctrl+alt+k neighboring_window up
# map ctrl+alt+j neighboring_window down
# map f1 copy_to_buffer a
# map f2 paste_from_buffer a
# map f3 copy_to_buffer b
# map f4 paste_from_buffer b

# Unicode input
map ctrl+shift+u kitten unicode_input

# Theme toggle (example)
# map ctrl+shift+t set_colors --all ~/.config/kitty/themes/light.conf

sync_to_monitor yes
# repaint_delay 10

# It Feels fast
repaint_delay 0

# Will this work?
# wayland_titlebar_color system
# allow_remote_control yes

enable_audio_bell yes
