#!/bin/bash

# Will start bluemail and kill its window only once it's loaded (like a background process since it can't by itself)
# Will also move the focus to the HDMI-A-1 monitor

blanket &
sleep 3

hyprctl dispatch focusmonitor HDMI-A-1
# (bluemail &) && sleep 5
# sleep 2 && hyprctl dispatch killactive && sleep 1
if [ $? -eq 0 ]; then

    hyprctl dispatch focusmonitor HDMI-A-1
    # then Start dolphin in a predefined position and reposition the mouse cursor to the right top corner
    # (dolphin &) && sleep 3 && hyprctl dispatch movecursortocorner 2 && hyprctl dispatch movetoworkspace ...
    # weektodo --enable-features=UseOzonePlatform --ozone-platform=wayland &
    sleep 1
    megasync &
    # foot &
    sleep 2
    /usr/bin/ticktick --enable-features=UseOzonePlatform --ozone-platform=wayland
    # hyprctl dispatch movecursortocorner 2
    # pkill foot
    # hyprctl dispatch togglespecialworkspace files
else
    notify-send "something went wrong"
fi
