#!/bin/bash

if pgrep -x "waybar" > /dev/null; then
    ~/.config/hypr/dots/.scripts/Hyprland/toggleFocusMode focus && killall waybar && waybar &
else
    ~/.config/hypr/dots/.scripts/Hyprland/toggleFocusMode focus && waybar & 
fi
