#!/bin/bash

source $HOME/.config/hypr/dots/.scripts/variables

ACTIVEWORKSPACE=$(hyprctl -j activeworkspace | jq -r '.name')
ACTIVEMONITOR=$(hyprctl -j activeworkspace | jq -r '.monitor')

moveToWorkspace() {
    local workspace_name=$1
    hyprctl dispatch workspace name:$workspace_name
}
workspacemonitor() {
    local wn=$1
    hyprctl -j workspaces | jq -r --arg name "$wn" '.[] | select(.name == $name) | .monitor'
}

moveworkspace_up() {
    if [[ $ACTIVEWORKSPACE == $WORKSPACE1 ]]; then
        moveToWorkspace $WORKSPACE2
        if [[ "$(workspacemonitor $WORKSPACE2)" == $ACTIVEMONITOR ]]; then
            break
        else
            moveToWorkspace $WORKSPACE1
            moveToWorkspace $WORKSPACE3
            if [[ "$(workspacemonitor $WORKSPACE3)" == $ACTIVEMONITOR ]]; then
                break
            else
                moveToWorkspace $WORKSPACE1
                moveToWorkspace $WORKSPACE4
                if [[ "$(workspacemonitor $WORKSPACE4)" == $ACTIVEMONITOR ]]; then
                    break
                else
                    moveToWorkspace $WORKSPACE1
                    moveToWorkspace $WORKSPACE5
                    if [[ "$(workspacemonitor $WORKSPACE5)" == $ACTIVEMONITOR ]]; then
                        break
                    else
                        moveToWorkspace $WORKSPACE1
                        moveToWorkspace $WORKSPACE6
                        if [[ "$(workspacemonitor $WORKSPACE6)" == $ACTIVEMONITOR ]]; then
                            break
                        else
                            moveToWorkspace $WORKSPACE1
                            moveToWorkspace $WORKSPACE7
                            if [[ "$(workspacemonitor $WORKSPACE7)" == $ACTIVEMONITOR ]]; then
                                break
                            else
                                moveToWorkspace $WORKSPACE1
                                moveToWorkspace $WORKSPACE8
                                if [[ "$(workspacemonitor $WORKSPACE8)" == $ACTIVEMONITOR ]]; then
                                    break
                                else
                                    moveToWorkspace $WORKSPACE1
                                    moveToWorkspace $WORKSPACE9
                                    if [[ "$(workspacemonitor $WORKSPACE9)" == $ACTIVEMONITOR ]]; then
                                        break
                                    else
                                        moveToWorkspace $WORKSPACE1
                                        moveToWorkspace $WORKSPACE0
                                        if [[ "$(workspacemonitor $WORKSPACE0)" == $ACTIVEMONITOR ]]; then
                                            break
                                        else
                                            moveToWorkspace $WORKSPACE1
                                        fi
                                    fi
                                fi
                            fi
                        fi
                    fi
                fi
            fi
        fi
    elif [[ $ACTIVEWORKSPACE == $WORKSPACE2 ]]; then
        moveToWorkspace $WORKSPACE3
        if [[ "$(workspacemonitor $WORKSPACE3)" == $ACTIVEMONITOR ]]; then
            break
        else
            moveToWorkspace $WORKSPACE2
            moveToWorkspace $WORKSPACE4
            if [[ "$(workspacemonitor $WORKSPACE4)" == $ACTIVEMONITOR ]]; then
                break
            else
                moveToWorkspace $WORKSPACE2
                moveToWorkspace $WORKSPACE5
                if [[ "$(workspacemonitor $WORKSPACE5)" == $ACTIVEMONITOR ]]; then
                    break
                else
                    moveToWorkspace $WORKSPACE2
                    moveToWorkspace $WORKSPACE6
                    if [[ "$(workspacemonitor $WORKSPACE6)" == $ACTIVEMONITOR ]]; then
                        break
                    else
                        moveToWorkspace $WORKSPACE2
                        moveToWorkspace $WORKSPACE7
                        if [[ "$(workspacemonitor $WORKSPACE7)" == $ACTIVEMONITOR ]]; then
                            break
                        else
                            moveToWorkspace $WORKSPACE2
                            moveToWorkspace $WORKSPACE8
                            if [[ "$(workspacemonitor $WORKSPACE8)" == $ACTIVEMONITOR ]]; then
                                break
                            else
                                moveToWorkspace $WORKSPACE2
                                moveToWorkspace $WORKSPACE9
                                if [[ "$(workspacemonitor $WORKSPACE9)" == $ACTIVEMONITOR ]]; then
                                    break
                                else
                                    moveToWorkspace $WORKSPACE2
                                    moveToWorkspace $WORKSPACE0
                                    if [[ "$(workspacemonitor $WORKSPACE0)" == $ACTIVEMONITOR ]]; then
                                        break
                                    else
                                        moveToWorkspace $WORKSPACE2
                                        moveToWorkspace $WORKSPACE1
                                        if [[ "$(workspacemonitor $WORKSPACE1)" == $ACTIVEMONITOR ]]; then
                                            break
                                        else
                                            moveToWorkspace $WORKSPACE2
                                        fi
                                    fi
                                fi
                            fi
                        fi
                    fi
                fi
            fi
        fi
    elif [[ $ACTIVEWORKSPACE == $WORKSPACE3 ]]; then
        moveToWorkspace $WORKSPACE4
        if [[ "$(workspacemonitor $WORKSPACE4)" == $ACTIVEMONITOR ]]; then
            break
        else
            moveToWorkspace $WORKSPACE3
            moveToWorkspace $WORKSPACE5
            if [[ "$(workspacemonitor $WORKSPACE5)" == $ACTIVEMONITOR ]]; then
                break
            else
                moveToWorkspace $WORKSPACE3
                moveToWorkspace $WORKSPACE6
                if [[ "$(workspacemonitor $WORKSPACE6)" == $ACTIVEMONITOR ]]; then
                    break
                else
                    moveToWorkspace $WORKSPACE3
                    moveToWorkspace $WORKSPACE7
                    if [[ "$(workspacemonitor $WORKSPACE7)" == $ACTIVEMONITOR ]]; then
                        break
                    else
                        moveToWorkspace $WORKSPACE3
                        moveToWorkspace $WORKSPACE8
                        if [[ "$(workspacemonitor $WORKSPACE8)" == $ACTIVEMONITOR ]]; then
                            break
                        else
                            moveToWorkspace $WORKSPACE3
                            moveToWorkspace $WORKSPACE9
                            if [[ "$(workspacemonitor $WORKSPACE9)" == $ACTIVEMONITOR ]]; then
                                break
                            else
                                moveToWorkspace $WORKSPACE3
                                moveToWorkspace $WORKSPACE0
                                if [[ "$(workspacemonitor $WORKSPACE0)" == $ACTIVEMONITOR ]]; then
                                    break
                                else
                                    moveToWorkspace $WORKSPACE3
                                    moveToWorkspace $WORKSPACE1
                                    if [[ "$(workspacemonitor $WORKSPACE1)" == $ACTIVEMONITOR ]]; then
                                        break
                                    else
                                        moveToWorkspace $WORKSPACE3
                                        moveToWorkspace $WORKSPACE2
                                        if [[ "$(workspacemonitor $WORKSPACE2)" == $ACTIVEMONITOR ]]; then
                                            break
                                        else
                                            moveToWorkspace $WORKSPACE3
                                        fi
                                    fi
                                fi
                            fi
                        fi
                    fi
                fi
            fi
        fi
    elif [[ $ACTIVEWORKSPACE == $WORKSPACE4 ]]; then
        moveToWorkspace $WORKSPACE5
        if [[ "$(workspacemonitor $WORKSPACE5)" == $ACTIVEMONITOR ]]; then
            break
        else
            moveToWorkspace $WORKSPACE4
            moveToWorkspace $WORKSPACE6
            if [[ "$(workspacemonitor $WORKSPACE6)" == $ACTIVEMONITOR ]]; then
                break
            else
                moveToWorkspace $WORKSPACE4
                moveToWorkspace $WORKSPACE7
                if [[ "$(workspacemonitor $WORKSPACE7)" == $ACTIVEMONITOR ]]; then
                    break
                else
                    moveToWorkspace $WORKSPACE4
                    moveToWorkspace $WORKSPACE8
                    if [[ "$(workspacemonitor $WORKSPACE8)" == $ACTIVEMONITOR ]]; then
                        break
                    else
                        moveToWorkspace $WORKSPACE4
                        moveToWorkspace $WORKSPACE9
                        if [[ "$(workspacemonitor $WORKSPACE9)" == $ACTIVEMONITOR ]]; then
                            break
                        else
                            moveToWorkspace $WORKSPACE4
                            moveToWorkspace $WORKSPACE0
                            if [[ "$(workspacemonitor $WORKSPACE0)" == $ACTIVEMONITOR ]]; then
                                break
                            else
                                moveToWorkspace $WORKSPACE4
                                moveToWorkspace $WORKSPACE1
                                if [[ "$(workspacemonitor $WORKSPACE1)" == $ACTIVEMONITOR ]]; then
                                    break
                                else
                                    moveToWorkspace $WORKSPACE4
                                    moveToWorkspace $WORKSPACE2
                                    if [[ "$(workspacemonitor $WORKSPACE2)" == $ACTIVEMONITOR ]]; then
                                        break
                                    else
                                        moveToWorkspace $WORKSPACE4
                                        moveToWorkspace $WORKSPACE3
                                        if [[ "$(workspacemonitor $WORKSPACE3)" == $ACTIVEMONITOR ]]; then
                                            break
                                        else
                                            moveToWorkspace $WORKSPACE4
                                        fi
                                    fi
                                fi
                            fi
                        fi
                    fi
                fi
            fi
        fi
    elif [[ $ACTIVEWORKSPACE == $WORKSPACE5 ]]; then
        moveToWorkspace $WORKSPACE6
        if [[ "$(workspacemonitor $WORKSPACE6)" == "$ACTIVEMONITOR" ]]; then
            break
        else
            moveToWorkspace $WORKSPACE5
            moveToWorkspace $WORKSPACE7
            if [[ "$(workspacemonitor $WORKSPACE7)" == "$ACTIVEMONITOR" ]]; then
                break
            else
                moveToWorkspace $WORKSPACE5
                moveToWorkspace $WORKSPACE8
                if [[ "$(workspacemonitor $WORKSPACE8)" == "$ACTIVEMONITOR" ]]; then
                    break
                else
                    moveToWorkspace $WORKSPACE5
                    moveToWorkspace $WORKSPACE9
                    if [[ "$(workspacemonitor $WORKSPACE9)" == $ACTIVEMONITOR ]]; then
                        break
                    else
                        moveToWorkspace $WORKSPACE5
                        moveToWorkspace $WORKSPACE0
                        if [[ "$(workspacemonitor $WORKSPACE0)" == $ACTIVEMONITOR ]]; then
                            break
                        else
                            moveToWorkspace $WORKSPACE5
                            moveToWorkspace $WORKSPACE1
                            if [[ "$(workspacemonitor $WORKSPACE1)" == $ACTIVEMONITOR ]]; then
                                break
                            else
                                moveToWorkspace $WORKSPACE5
                                moveToWorkspace $WORKSPACE2
                                if [[ "$(workspacemonitor $WORKSPACE2)" == $ACTIVEMONITOR ]]; then
                                    break
                                else
                                    moveToWorkspace $WORKSPACE5
                                    moveToWorkspace $WORKSPACE3
                                    if [[ "$(workspacemonitor $WORKSPACE3)" == $ACTIVEMONITOR ]]; then
                                        break
                                    else
                                        moveToWorkspace $WORKSPACE5
                                        moveToWorkspace $WORKSPACE4
                                        if [[ "$(workspacemonitor $WORKSPACE4)" == "$ACTIVEMONITOR" ]]; then
                                            break
                                        else
                                            moveToWorkspace $WORKSPACE5
                                        fi
                                    fi
                                fi
                            fi
                        fi
                    fi
                fi
            fi
        fi

    elif [[ $ACTIVEWORKSPACE == $WORKSPACE6 ]]; then
        moveToWorkspace $WORKSPACE7
        if [[ "$(workspacemonitor $WORKSPACE7)" == "$ACTIVEMONITOR" ]]; then
            break
        elif [[ "$(workspacemonitor $WORKSPACE7)" == "$ACTIVEMONITOR" ]]; then
            moveToWorkspace $WORKSPACE6
            moveToWorkspace $WORKSPACE8
            if [[ "$(workspacemonitor $WORKSPACE8)" == "$ACTIVEMONITOR" ]]; then
                break
            else
                moveToWorkspace $WORKSPACE6
                moveToWorkspace $WORKSPACE9
                if [[ "$(workspacemonitor $WORKSPACE9)" == "$ACTIVEMONITOR" ]]; then
                    break
                else
                    moveToWorkspace $WORKSPACE6
                    moveToWorkspace $WORKSPACE0
                    if [[ "$(workspacemonitor $WORKSPACE0)" == "$ACTIVEMONITOR" ]]; then
                        break
                    else
                        moveToWorkspace $WORKSPACE6
                        moveToWorkspace $WORKSPACE1
                        if [[ "$(workspacemonitor $WORKSPACE1)" == "$ACTIVEMONITOR" ]]; then
                            break
                        else
                            moveToWorkspace $WORKSPACE6
                            moveToWorkspace $WORKSPACE2
                            if [[ "$(workspacemonitor $WORKSPACE2)" == "$ACTIVEMONITOR" ]]; then
                                break
                            else
                                moveToWorkspace $WORKSPACE6
                                moveToWorkspace $WORKSPACE3
                                if [[ "$(workspacemonitor $WORKSPACE3)" == "$ACTIVEMONITOR" ]]; then
                                    break
                                else
                                    moveToWorkspace $WORKSPACE6
                                    moveToWorkspace $WORKSPACE4
                                    if [[ "$(workspacemonitor $WORKSPACE4)" == "$ACTIVEMONITOR" ]]; then
                                        break
                                    else
                                        moveToWorkspace $WORKSPACE6
                                        moveToWorkspace $WORKSPACE5
                                        if [[ "$(workspacemonitor $WORKSPACE5)" == "$ACTIVEMONITOR" ]]; then
                                            break
                                        else
                                            moveToWorkspace $WORKSPACE6
                                        fi
                                    fi
                                fi
                            fi
                        fi
                    fi
                fi
            fi
        fi
    elif [[ $ACTIVEWORKSPACE == $WORKSPACE7 ]]; then
        moveToWorkspace $WORKSPACE8
        if [[ "$(workspacemonitor $WORKSPACE8)" == "$ACTIVEMONITOR" ]]; then
            break
        else
            moveToWorkspace $WORKSPACE7
            moveToWorkspace $WORKSPACE9
            if [[ "$(workspacemonitor $WORKSPACE9)" == "$ACTIVEMONITOR" ]]; then
                break
            else
                moveToWorkspace $WORKSPACE7
                moveToWorkspace $WORKSPACE0
                if [[ "$(workspacemonitor $WORKSPACE0)" == "$ACTIVEMONITOR" ]]; then
                    break
                else
                    moveToWorkspace $WORKSPACE7
                    moveToWorkspace $WORKSPACE1
                    if [[ "$(workspacemonitor $WORKSPACE1)" == "$ACTIVEMONITOR" ]]; then
                        break
                    else
                        moveToWorkspace $WORKSPACE7
                        moveToWorkspace $WORKSPACE2
                        if [[ "$(workspacemonitor $WORKSPACE2)" == "$ACTIVEMONITOR" ]]; then
                            break
                        else
                            moveToWorkspace $WORKSPACE7
                            moveToWorkspace $WORKSPACE3
                            if [[ "$(workspacemonitor $WORKSPACE3)" == "$ACTIVEMONITOR" ]]; then
                                break
                            else
                                moveToWorkspace $WORKSPACE7
                                moveToWorkspace $WORKSPACE4
                                if [[ "$(workspacemonitor $WORKSPACE4)" == "$ACTIVEMONITOR" ]]; then
                                    break
                                else
                                    moveToWorkspace $WORKSPACE7
                                    moveToWorkspace $WORKSPACE5
                                    if [[ "$(workspacemonitor $WORKSPACE5)" == $ACTIVEMONITOR ]]; then
                                        break
                                    else
                                        moveToWorkspace $WORKSPACE7
                                        moveToWorkspace $WORKSPACE6
                                        if [[ "$(workspacemonitor $WORKSPACE6)" == "$ACTIVEMONITOR" ]]; then
                                            break
                                        else
                                            moveToWorkspace $WORKSPACE7
                                        fi
                                    fi
                                fi
                            fi
                        fi
                    fi
                fi
            fi
        fi
    elif [[ $ACTIVEWORKSPACE == $WORKSPACE8 ]]; then
        moveToWorkspace $WORKSPACE9
        if [[ "$(workspacemonitor $WORKSPACE9)" == "$ACTIVEMONITOR" ]]; then
            break
        else
            moveToWorkspace $WORKSPACE8
            moveToWorkspace $WORKSPACE0
            if [[ "$(workspacemonitor $WORKSPACE0)" == "$ACTIVEMONITOR" ]]; then
                break
            else
                moveToWorkspace $WORKSPACE8
                moveToWorkspace $WORKSPACE1
                if [[ "$(workspacemonitor $WORKSPACE1)" == "$ACTIVEMONITOR" ]]; then
                    break
                else
                    moveToWorkspace $WORKSPACE8
                    moveToWorkspace $WORKSPACE2
                    if [[ "$(workspacemonitor $WORKSPACE2)" == "$ACTIVEMONITOR" ]]; then
                        break
                    else
                        moveToWorkspace $WORKSPACE8
                        moveToWorkspace $WORKSPACE3
                        if [[ "$(workspacemonitor $WORKSPACE3)" == "$ACTIVEMONITOR" ]]; then
                            break
                        else
                            moveToWorkspace $WORKSPACE8
                            moveToWorkspace $WORKSPACE4
                            if [[ "$(workspacemonitor $WORKSPACE4)" == "$ACTIVEMONITOR" ]]; then
                                break
                            else
                                moveToWorkspace $WORKSPACE8
                                moveToWorkspace $WORKSPACE5
                                if [[ "$(workspacemonitor $WORKSPACE5)" == "$ACTIVEMONITOR" ]]; then
                                    break
                                else
                                    moveToWorkspace $WORKSPACE8
                                    moveToWorkspace $WORKSPACE6
                                    if [[ "$(workspacemonitor $WORKSPACE6)" == "$ACTIVEMONITOR" ]]; then
                                        break
                                    else
                                        moveToWorkspace $WORKSPACE8
                                        moveToWorkspace $WORKSPACE7
                                        if [[ "$(workspacemonitor $WORKSPACE7)" == "$ACTIVEMONITOR" ]]; then
                                            break
                                        else
                                            moveToWorkspace $WORKSPACE8
                                        fi
                                    fi
                                fi
                            fi
                        fi
                    fi
                fi
            fi
        fi
    elif [[ $ACTIVEWORKSPACE == $WORKSPACE9 ]]; then
        moveToWorkspace $WORKSPACE0
        if [[ "$(workspacemonitor $WORKSPACE0)" == "$ACTIVEMONITOR" ]]; then
            break
        else
            moveToWorkspace $WORKSPACE9
            moveToWorkspace $WORKSPACE1
            if [[ "$(workspacemonitor $WORKSPACE1)" == "$ACTIVEMONITOR" ]]; then
                break
            else
                moveToWorkspace $WORKSPACE9
                moveToWorkspace $WORKSPACE2
                if [[ "$(workspacemonitor $WORKSPACE2)" == "$ACTIVEMONITOR" ]]; then
                    break
                else
                    moveToWorkspace $WORKSPACE9
                    moveToWorkspace $WORKSPACE3
                    if [[ "$(workspacemonitor $WORKSPACE3)" == "$ACTIVEMONITOR" ]]; then
                        break
                    else
                        moveToWorkspace $WORKSPACE9
                        moveToWorkspace $WORKSPACE4
                        if [[ "$(workspacemonitor $WORKSPACE4)" == "$ACTIVEMONITOR" ]]; then
                            break
                        else
                            moveToWorkspace $WORKSPACE9
                            moveToWorkspace $WORKSPACE5
                            if [[ "$(workspacemonitor $WORKSPACE5)" == "$ACTIVEMONITOR" ]]; then
                                break
                            else
                                moveToWorkspace $WORKSPACE9
                                moveToWorkspace $WORKSPACE6
                                if [[ "$(workspacemonitor $WORKSPACE6)" == "$ACTIVEMONITOR" ]]; then
                                    break
                                else
                                    moveToWorkspace $WORKSPACE9
                                    moveToWorkspace $WORKSPACE7
                                    if [[ "$(workspacemonitor $WORKSPACE7)" == "$ACTIVEMONITOR" ]]; then
                                        break
                                    else
                                        moveToWorkspace $WORKSPACE9
                                        moveToWorkspace $WORKSPACE8
                                        if [[ "$(workspacemonitor $WORKSPACE8)" == "$ACTIVEMONITOR" ]]; then
                                            break
                                        else
                                            moveToWorkspace $WORKSPACE9
                                        fi
                                    fi
                                fi
                            fi
                        fi
                    fi
                fi
            fi
        fi
    elif [[ $ACTIVEWORKSPACE == $WORKSPACE0 ]]; then
        moveToWorkspace $WORKSPACE1
        if [[ "$(workspacemonitor $WORKSPACE1)" == "$ACTIVEMONITOR" ]]; then
            break
        else
            moveToWorkspace $WORKSPACE0
            moveToWorkspace $WORKSPACE2
            if [[ "$(workspacemonitor $WORKSPACE2)" == "$ACTIVEMONITOR" ]]; then
                break
            else
                moveToWorkspace $WORKSPACE0
                moveToWorkspace $WORKSPACE3
                if [[ "$(workspacemonitor $WORKSPACE3)" == "$ACTIVEMONITOR" ]]; then
                    break
                else
                    moveToWorkspace $WORKSPACE0
                    moveToWorkspace $WORKSPACE4
                    if [[ "$(workspacemonitor $WORKSPACE4)" == "$ACTIVEMONITOR" ]]; then
                        break
                    else
                        moveToWorkspace $WORKSPACE0
                        moveToWorkspace $WORKSPACE5
                        if [[ "$(workspacemonitor $WORKSPACE5)" == "$ACTIVEMONITOR" ]]; then
                            break
                        else
                            moveToWorkspace $WORKSPACE0
                            moveToWorkspace $WORKSPACE6
                            if [[ "$(workspacemonitor $WORKSPACE6)" == "$ACTIVEMONITOR" ]]; then
                                break
                            else
                                moveToWorkspace $WORKSPACE0
                                moveToWorkspace $WORKSPACE7
                                if [[ "$(workspacemonitor $WORKSPACE7)" == "$ACTIVEMONITOR" ]]; then
                                    break
                                else
                                    moveToWorkspace $WORKSPACE0
                                    moveToWorkspace $WORKSPACE8
                                    if [[ "$(workspacemonitor $WORKSPACE8)" == "$ACTIVEMONITOR" ]]; then
                                        break
                                    else
                                        moveToWorkspace $WORKSPACE0
                                        moveToWorkspace $WORKSPACE9
                                        if [[ "$(workspacemonitor $WORKSPACE9)" == "$ACTIVEMONITOR" ]]; then
                                            break
                                        else
                                            moveToWorkspace $WORKSPACE0
                                        fi
                                    fi
                                fi
                            fi
                        fi
                    fi
                fi
            fi
        fi
    fi
}

moveworkspace_down() {
    if [[ $ACTIVEWORKSPACE == $WORKSPACE0 ]]; then
        moveToWorkspace $WORKSPACE9
        if [[ "$(workspacemonitor $WORKSPACE9)" == "$ACTIVEMONITOR" ]]; then
            break
        else
            moveToWorkspace $WORKSPACE0
            moveToWorkspace $WORKSPACE8
            if [[ "$(workspacemonitor $WORKSPACE8)" == "$ACTIVEMONITOR" ]]; then
                break
            else
                moveToWorkspace $WORKSPACE0
                moveToWorkspace $WORKSPACE7
                if [[ "$(workspacemonitor $WORKSPACE7)" == "$ACTIVEMONITOR" ]]; then
                    break
                else
                    moveToWorkspace $WORKSPACE0
                    moveToWorkspace $WORKSPACE6
                    if [[ "$(workspacemonitor $WORKSPACE6)" == "$ACTIVEMONITOR" ]]; then
                        break
                    else
                        moveToWorkspace $WORKSPACE0
                        moveToWorkspace $WORKSPACE5
                        if [[ "$(workspacemonitor $WORKSPACE5)" == "$ACTIVEMONITOR" ]]; then
                            break
                        else
                            moveToWorkspace $WORKSPACE0
                            moveToWorkspace $WORKSPACE4
                            if [[ "$(workspacemonitor $WORKSPACE4)" == "$ACTIVEMONITOR" ]]; then
                                break
                            else
                                moveToWorkspace $WORKSPACE0
                                moveToWorkspace $WORKSPACE3
                                if [[ "$(workspacemonitor $WORKSPACE3)" == "$ACTIVEMONITOR" ]]; then
                                    break
                                else
                                    moveToWorkspace $WORKSPACE0
                                    moveToWorkspace $WORKSPACE2
                                    if [[ "$(workspacemonitor $WORKSPACE2)" == "$ACTIVEMONITOR" ]]; then
                                        break
                                    else
                                        moveToWorkspace $WORKSPACE0
                                        moveToWorkspace $WORKSPACE1
                                        if [[ "$(workspacemonitor $WORKSPACE1)" == "$ACTIVEMONITOR" ]]; then
                                            break
                                        else
                                            moveToWorkspace $WORKSPACE0
                                        fi
                                    fi
                                fi
                            fi
                        fi
                    fi
                fi
            fi
        fi
    elif [[ $ACTIVEWORKSPACE == $WORKSPACE9 ]]; then
        moveToWorkspace $WORKSPACE8
        if [[ "$(workspacemonitor $WORKSPACE8)" == "$ACTIVEMONITOR" ]]; then
            break
        else
            moveToWorkspace $WORKSPACE9
            moveToWorkspace $WORKSPACE7
            if [[ "$(workspacemonitor $WORKSPACE7)" == "$ACTIVEMONITOR" ]]; then
                break
            else
                moveToWorkspace $WORKSPACE9
                moveToWorkspace $WORKSPACE6
                if [[ "$(workspacemonitor $WORKSPACE6)" == "$ACTIVEMONITOR" ]]; then
                    break
                else
                    moveToWorkspace $WORKSPACE9
                    moveToWorkspace $WORKSPACE5
                    if [[ "$(workspacemonitor $WORKSPACE5)" == "$ACTIVEMONITOR" ]]; then
                        break
                    else
                        moveToWorkspace $WORKSPACE9
                        moveToWorkspace $WORKSPACE4
                        if [[ "$(workspacemonitor $WORKSPACE4)" == "$ACTIVEMONITOR" ]]; then
                            break
                        else
                            moveToWorkspace $WORKSPACE9
                            moveToWorkspace $WORKSPACE3
                            if [[ "$(workspacemonitor $WORKSPACE3)" == "$ACTIVEMONITOR" ]]; then
                                break
                            else
                                moveToWorkspace $WORKSPACE9
                                moveToWorkspace $WORKSPACE2
                                if [[ "$(workspacemonitor $WORKSPACE2)" == "$ACTIVEMONITOR" ]]; then
                                    break
                                else
                                    moveToWorkspace $WORKSPACE9
                                    moveToWorkspace $WORKSPACE1
                                    if [[ "$(workspacemonitor $WORKSPACE1)" == "$ACTIVEMONITOR" ]]; then
                                        break
                                    else
                                        moveToWorkspace $WORKSPACE9
                                        moveToWorkspace $WORKSPACE0
                                        if [[ "$(workspacemonitor $WORKSPACE0)" == "$ACTIVEMONITOR" ]]; then
                                            break
                                        else
                                            moveToWorkspace $WORKSPACE9
                                        fi
                                    fi
                                fi
                            fi
                        fi
                    fi
                fi
            fi
        fi
    elif [[ $ACTIVEWORKSPACE == $WORKSPACE8 ]]; then
        moveToWorkspace $WORKSPACE7
        if [[ "$(workspacemonitor $WORKSPACE7)" == "$ACTIVEMONITOR" ]]; then
            break
        else
            moveToWorkspace $WORKSPACE8
            moveToWorkspace $WORKSPACE6
            if [[ "$(workspacemonitor $WORKSPACE6)" == "$ACTIVEMONITOR" ]]; then
                break
            else
                moveToWorkspace $WORKSPACE8
                moveToWorkspace $WORKSPACE5
                if [[ "$(workspacemonitor $WORKSPACE5)" == "$ACTIVEMONITOR" ]]; then
                    break
                else
                    moveToWorkspace $WORKSPACE8
                    moveToWorkspace $WORKSPACE4
                    if [[ "$(workspacemonitor $WORKSPACE4)" == "$ACTIVEMONITOR" ]]; then
                        break
                    else
                        moveToWorkspace $WORKSPACE8
                        moveToWorkspace $WORKSPACE3
                        if [[ "$(workspacemonitor $WORKSPACE3)" == "$ACTIVEMONITOR" ]]; then
                            break
                        else
                            moveToWorkspace $WORKSPACE8
                            moveToWorkspace $WORKSPACE2
                            if [[ "$(workspacemonitor $WORKSPACE2)" == "$ACTIVEMONITOR" ]]; then
                                break
                            else
                                moveToWorkspace $WORKSPACE8
                                moveToWorkspace $WORKSPACE1
                                if [[ "$(workspacemonitor $WORKSPACE1)" == "$ACTIVEMONITOR" ]]; then
                                    break
                                else
                                    moveToWorkspace $WORKSPACE8
                                    moveToWorkspace $WORKSPACE0
                                    if [[ "$(workspacemonitor $WORKSPACE0)" == "$ACTIVEMONITOR" ]]; then
                                        break
                                    else
                                        moveToWorkspace $WORKSPACE8
                                        moveToWorkspace $WORKSPACE9
                                        if [[ "$(workspacemonitor $WORKSPACE9)" == "$ACTIVEMONITOR" ]]; then
                                            break
                                        else
                                            moveToWorkspace $WORKSPACE8
                                        fi
                                    fi
                                fi
                            fi
                        fi
                    fi
                fi
            fi
        fi
    elif [[ $ACTIVEWORKSPACE == $WORKSPACE7 ]]; then
        moveToWorkspace $WORKSPACE6
        if [[ "$(workspacemonitor $WORKSPACE6)" == "$ACTIVEMONITOR" ]]; then
            break
        else
            moveToWorkspace $WORKSPACE7
            moveToWorkspace $WORKSPACE5
            if [[ "$(workspacemonitor $WORKSPACE5)" == "$ACTIVEMONITOR" ]]; then
                break
            else
                moveToWorkspace $WORKSPACE7
                moveToWorkspace $WORKSPACE4
                if [[ "$(workspacemonitor $WORKSPACE4)" == "$ACTIVEMONITOR" ]]; then
                    break
                else
                    moveToWorkspace $WORKSPACE7
                    moveToWorkspace $WORKSPACE3
                    if [[ "$(workspacemonitor $WORKSPACE3)" == "$ACTIVEMONITOR" ]]; then
                        break
                    else
                        moveToWorkspace $WORKSPACE7
                        moveToWorkspace $WORKSPACE2
                        if [[ "$(workspacemonitor $WORKSPACE2)" == "$ACTIVEMONITOR" ]]; then
                            break
                        else
                            moveToWorkspace $WORKSPACE7
                            moveToWorkspace $WORKSPACE1
                            if [[ "$(workspacemonitor $WORKSPACE1)" == "$ACTIVEMONITOR" ]]; then
                                break
                            else
                                moveToWorkspace $WORKSPACE7
                                moveToWorkspace $WORKSPACE0
                                if [[ "$(workspacemonitor $WORKSPACE0)" == "$ACTIVEMONITOR" ]]; then
                                    break
                                else
                                    moveToWorkspace $WORKSPACE7
                                    moveToWorkspace $WORKSPACE9
                                    if [[ "$(workspacemonitor $WORKSPACE9)" == "$ACTIVEMONITOR" ]]; then
                                        break
                                    else
                                        moveToWorkspace $WORKSPACE7
                                        moveToWorkspace $WORKSPACE8
                                        if [[ "$(workspacemonitor $WORKSPACE8)" == "$ACTIVEMONITOR" ]]; then
                                            break
                                        else
                                            moveToWorkspace $WORKSPACE7
                                        fi
                                    fi
                                fi
                            fi
                        fi
                    fi
                fi
            fi
        fi
    elif [[ $ACTIVEWORKSPACE == $WORKSPACE6 ]]; then
        moveToWorkspace $WORKSPACE5
        if [[ "$(workspacemonitor $WORKSPACE5)" == "$ACTIVEMONITOR" ]]; then
            break
        else
            moveToWorkspace $WORKSPACE6
            moveToWorkspace $WORKSPACE4
            if [[ "$(workspacemonitor $WORKSPACE4)" == "$ACTIVEMONITOR" ]]; then
                break
            else
                moveToWorkspace $WORKSPACE6
                moveToWorkspace $WORKSPACE3
                if [[ "$(workspacemonitor $WORKSPACE3)" == "$ACTIVEMONITOR" ]]; then
                    break
                else
                    moveToWorkspace $WORKSPACE6
                    moveToWorkspace $WORKSPACE2
                    if [[ "$(workspacemonitor $WORKSPACE2)" == "$ACTIVEMONITOR" ]]; then
                        break
                    else
                        moveToWorkspace $WORKSPACE6
                        moveToWorkspace $WORKSPACE1
                        if [[ "$(workspacemonitor $WORKSPACE1)" == "$ACTIVEMONITOR" ]]; then
                            break
                        else
                            moveToWorkspace $WORKSPACE6
                            moveToWorkspace $WORKSPACE0
                            if [[ "$(workspacemonitor $WORKSPACE0)" == "$ACTIVEMONITOR" ]]; then
                                break
                            else
                                moveToWorkspace $WORKSPACE6
                                moveToWorkspace $WORKSPACE9
                                if [[ "$(workspacemonitor $WORKSPACE9)" == "$ACTIVEMONITOR" ]]; then
                                    break
                                else
                                    moveToWorkspace $WORKSPACE6
                                    moveToWorkspace $WORKSPACE8
                                    if [[ "$(workspacemonitor $WORKSPACE8)" == "$ACTIVEMONITOR" ]]; then
                                        break
                                    else
                                        moveToWorkspace $WORKSPACE6
                                        moveToWorkspace $WORKSPACE7
                                        if [[ "$(workspacemonitor $WORKSPACE7)" == "$ACTIVEMONITOR" ]]; then
                                            break
                                        else
                                            moveToWorkspace $WORKSPACE6
                                        fi
                                    fi
                                fi
                            fi
                        fi
                    fi
                fi
            fi
        fi
    elif [[ $ACTIVEWORKSPACE == $WORKSPACE5 ]]; then
        moveToWorkspace $WORKSPACE4
        if [[ "$(workspacemonitor $WORKSPACE4)" == "$ACTIVEMONITOR" ]]; then
            break
        else
            moveToWorkspace $WORKSPACE5
            moveToWorkspace $WORKSPACE3
            if [[ "$(workspacemonitor $WORKSPACE3)" == "$ACTIVEMONITOR" ]]; then
                break
            else
                moveToWorkspace $WORKSPACE5
                moveToWorkspace $WORKSPACE2
                if [[ "$(workspacemonitor $WORKSPACE2)" == "$ACTIVEMONITOR" ]]; then
                    break
                else
                    moveToWorkspace $WORKSPACE5
                    moveToWorkspace $WORKSPACE1
                    if [[ "$(workspacemonitor $WORKSPACE1)" == "$ACTIVEMONITOR" ]]; then
                        break
                    else
                        moveToWorkspace $WORKSPACE5
                        moveToWorkspace $WORKSPACE0
                        if [[ "$(workspacemonitor $WORKSPACE0)" == "$ACTIVEMONITOR" ]]; then
                            break
                        else
                            moveToWorkspace $WORKSPACE5
                            moveToWorkspace $WORKSPACE9
                            if [[ "$(workspacemonitor $WORKSPACE9)" == "$ACTIVEMONITOR" ]]; then
                                break
                            else
                                moveToWorkspace $WORKSPACE5
                                moveToWorkspace $WORKSPACE8
                                if [[ "$(workspacemonitor $WORKSPACE8)" == "$ACTIVEMONITOR" ]]; then
                                    break
                                else
                                    moveToWorkspace $WORKSPACE5
                                    moveToWorkspace $WORKSPACE7
                                    if [[ "$(workspacemonitor $WORKSPACE7)" == "$ACTIVEMONITOR" ]]; then
                                        break
                                    else
                                        moveToWorkspace $WORKSPACE5
                                        moveToWorkspace $WORKSPACE6
                                        if [[ "$(workspacemonitor $WORKSPACE6)" == "$ACTIVEMONITOR" ]]; then
                                            break
                                        else
                                            moveToWorkspace $WORKSPACE5
                                        fi
                                    fi
                                fi
                            fi
                        fi
                    fi
                fi
            fi
        fi
    elif [[ $ACTIVEWORKSPACE == $WORKSPACE4 ]]; then
        moveToWorkspace $WORKSPACE3
        if [[ "$(workspacemonitor $WORKSPACE3)" == "$ACTIVEMONITOR" ]]; then
            break
        else
            moveToWorkspace $WORKSPACE4
            moveToWorkspace $WORKSPACE2
            if [[ "$(workspacemonitor $WORKSPACE2)" == "$ACTIVEMONITOR" ]]; then
                break
            else
                moveToWorkspace $WORKSPACE4
                moveToWorkspace $WORKSPACE1
                if [[ "$(workspacemonitor $WORKSPACE1)" == "$ACTIVEMONITOR" ]]; then
                    break
                else
                    moveToWorkspace $WORKSPACE4
                    moveToWorkspace $WORKSPACE0
                    if [[ "$(workspacemonitor $WORKSPACE0)" == "$ACTIVEMONITOR" ]]; then
                        break
                    else
                        moveToWorkspace $WORKSPACE4
                        moveToWorkspace $WORKSPACE9
                        if [[ "$(workspacemonitor $WORKSPACE9)" == "$ACTIVEMONITOR" ]]; then
                            break
                        else
                            moveToWorkspace $WORKSPACE4
                            moveToWorkspace $WORKSPACE8
                            if [[ "$(workspacemonitor $WORKSPACE8)" == "$ACTIVEMONITOR" ]]; then
                                break
                            else
                                moveToWorkspace $WORKSPACE4
                                moveToWorkspace $WORKSPACE7
                                if [[ "$(workspacemonitor $WORKSPACE7)" == "$ACTIVEMONITOR" ]]; then
                                    break
                                else
                                    moveToWorkspace $WORKSPACE4
                                    moveToWorkspace $WORKSPACE6
                                    if [[ "$(workspacemonitor $WORKSPACE6)" == "$ACTIVEMONITOR" ]]; then
                                        break
                                    else
                                        moveToWorkspace $WORKSPACE4
                                        moveToWorkspace $WORKSPACE5
                                        if [[ "$(workspacemonitor $WORKSPACE5)" == "$ACTIVEMONITOR" ]]; then
                                            break
                                        else
                                            moveToWorkspace $WORKSPACE4
                                        fi
                                    fi
                                fi
                            fi
                        fi
                    fi
                fi
            fi
        fi
    elif [[ $ACTIVEWORKSPACE == $WORKSPACE3 ]]; then
        moveToWorkspace $WORKSPACE2
        if [[ "$(workspacemonitor $WORKSPACE2)" == "$ACTIVEMONITOR" ]]; then
            break
        else
            moveToWorkspace $WORKSPACE3
            moveToWorkspace $WORKSPACE1
            if [[ "$(workspacemonitor $WORKSPACE1)" == "$ACTIVEMONITOR" ]]; then
                break
            else
                moveToWorkspace $WORKSPACE3
                moveToWorkspace $WORKSPACE0
                if [[ "$(workspacemonitor $WORKSPACE0)" == "$ACTIVEMONITOR" ]]; then
                    break
                else
                    moveToWorkspace $WORKSPACE3
                    moveToWorkspace $WORKSPACE9
                    if [[ "$(workspacemonitor $WORKSPACE9)" == "$ACTIVEMONITOR" ]]; then
                        break
                    else
                        moveToWorkspace $WORKSPACE3
                        moveToWorkspace $WORKSPACE8
                        if [[ "$(workspacemonitor $WORKSPACE8)" == "$ACTIVEMONITOR" ]]; then
                            break
                        else
                            moveToWorkspace $WORKSPACE3
                            moveToWorkspace $WORKSPACE7
                            if [[ "$(workspacemonitor $WORKSPACE7)" == "$ACTIVEMONITOR" ]]; then
                                break
                            else
                                moveToWorkspace $WORKSPACE3
                                moveToWorkspace $WORKSPACE6
                                if [[ "$(workspacemonitor $WORKSPACE6)" == "$ACTIVEMONITOR" ]]; then
                                    break
                                else
                                    moveToWorkspace $WORKSPACE3
                                    moveToWorkspace $WORKSPACE5
                                    if [[ "$(workspacemonitor $WORKSPACE5)" == "$ACTIVEMONITOR" ]]; then
                                        break
                                    else
                                        moveToWorkspace $WORKSPACE3
                                        moveToWorkspace $WORKSPACE4
                                        if [[ "$(workspacemonitor $WORKSPACE4)" == "$ACTIVEMONITOR" ]]; then
                                            break
                                        else
                                            moveToWorkspace $WORKSPACE3
                                        fi
                                    fi
                                fi
                            fi
                        fi
                    fi
                fi
            fi
        fi
    elif [[ $ACTIVEWORKSPACE == $WORKSPACE2 ]]; then
        moveToWorkspace $WORKSPACE1
        if [[ "$(workspacemonitor $WORKSPACE1)" == "$ACTIVEMONITOR" ]]; then
            break
        else
            moveToWorkspace $WORKSPACE2
            moveToWorkspace $WORKSPACE0
            if [[ "$(workspacemonitor $WORKSPACE0)" == "$ACTIVEMONITOR" ]]; then
                break
            else
                moveToWorkspace $WORKSPACE2
                moveToWorkspace $WORKSPACE9
                if [[ "$(workspacemonitor $WORKSPACE9)" == "$ACTIVEMONITOR" ]]; then
                    break
                else
                    moveToWorkspace $WORKSPACE2
                    moveToWorkspace $WORKSPACE8
                    if [[ "$(workspacemonitor $WORKSPACE8)" == "$ACTIVEMONITOR" ]]; then
                        break
                    else
                        moveToWorkspace $WORKSPACE2
                        moveToWorkspace $WORKSPACE7
                        if [[ "$(workspacemonitor $WORKSPACE7)" == "$ACTIVEMONITOR" ]]; then
                            break
                        else
                            moveToWorkspace $WORKSPACE2
                            moveToWorkspace $WORKSPACE6
                            if [[ "$(workspacemonitor $WORKSPACE6)" == "$ACTIVEMONITOR" ]]; then
                                break
                            else
                                moveToWorkspace $WORKSPACE2
                                moveToWorkspace $WORKSPACE5
                                if [[ "$(workspacemonitor $WORKSPACE5)" == "$ACTIVEMONITOR" ]]; then
                                    break
                                else
                                    moveToWorkspace $WORKSPACE2
                                    moveToWorkspace $WORKSPACE4
                                    if [[ "$(workspacemonitor $WORKSPACE4)" == "$ACTIVEMONITOR" ]]; then
                                        break
                                    else
                                        moveToWorkspace $WORKSPACE2
                                        moveToWorkspace $WORKSPACE3
                                        if [[ "$(workspacemonitor $WORKSPACE3)" == "$ACTIVEMONITOR" ]]; then
                                            break
                                        else
                                            moveToWorkspace $WORKSPACE2
                                        fi
                                    fi
                                fi
                            fi
                        fi
                    fi
                fi
            fi
        fi
    elif [[ $ACTIVEWORKSPACE == $WORKSPACE1 ]]; then
        moveToWorkspace $WORKSPACE0
        if [[ "$(workspacemonitor $WORKSPACE0)" == "$ACTIVEMONITOR" ]]; then
            break
        else
            moveToWorkspace $WORKSPACE1
            moveToWorkspace $WORKSPACE9
            if [[ "$(workspacemonitor $WORKSPACE9)" == "$ACTIVEMONITOR" ]]; then
                break
            else
                moveToWorkspace $WORKSPACE1
                moveToWorkspace $WORKSPACE8
                if [[ "$(workspacemonitor $WORKSPACE8)" == "$ACTIVEMONITOR" ]]; then
                    break
                else
                    moveToWorkspace $WORKSPACE1
                    moveToWorkspace $WORKSPACE7
                    if [[ "$(workspacemonitor $WORKSPACE7)" == "$ACTIVEMONITOR" ]]; then
                        break
                    else
                        moveToWorkspace $WORKSPACE1
                        moveToWorkspace $WORKSPACE6
                        if [[ "$(workspacemonitor $WORKSPACE6)" == "$ACTIVEMONITOR" ]]; then
                            break
                        else
                            moveToWorkspace $WORKSPACE1
                            moveToWorkspace $WORKSPACE5
                            if [[ "$(workspacemonitor $WORKSPACE5)" == "$ACTIVEMONITOR" ]]; then
                                break
                            else
                                moveToWorkspace $WORKSPACE1
                                moveToWorkspace $WORKSPACE4
                                if [[ "$(workspacemonitor $WORKSPACE4)" == "$ACTIVEMONITOR" ]]; then
                                    break
                                else
                                    moveToWorkspace $WORKSPACE1
                                    moveToWorkspace $WORKSPACE3
                                    if [[ "$(workspacemonitor $WORKSPACE3)" == "$ACTIVEMONITOR" ]]; then
                                        break
                                    else
                                        moveToWorkspace $WORKSPACE1
                                        moveToWorkspace $WORKSPACE2
                                        if [[ "$(workspacemonitor $WORKSPACE2)" == "$ACTIVEMONITOR" ]]; then
                                            break
                                        else
                                            moveToWorkspace $WORKSPACE1
                                        fi
                                    fi
                                fi
                            fi
                        fi
                    fi
                fi
            fi
        fi
    fi
}

case "$1" in
up)
    moveworkspace_up
    ;;
down)
    moveworkspace_down
    ;;
esac
