#!/usr/bin/env bash

ACTIVEWORKSPACE=$(hyprctl -j activeworkspace | jq -r '.name')
ACTIVEMONITOR=$(hyprctl -j activeworkspace | jq -r '.monitor')
WORKSPACE1='A:Web'
WORKSPACE2='B:Editor'
WORKSPACE3='C:Term'
WORKSPACE4='D:Book'
WORKSPACE5='E:Multimedia'
WORKSPACE8='F:System'
WORKSPACE9='G:Office'
WORKSPACE0='H:Other'

moveToWorkspace() {
    local workspace_name=$1
    hyprctl dispatch workspace name:$workspace_name
}
workspacemonitor() {
    local wn=$1
    hyprctl -j workspaces | jq -r --arg name "$wn" '.[] | select(.name == $name) | .monitor'
}

moveworkspace_up() {
    if [[ $ACTIVEWORKSPACE == $WORKSPACE1 ]]; then
        moveToWorkspace B:Editor
        if [[ "$(workspacemonitor $WORKSPACE2)" == $ACTIVEMONITOR ]]; then
            break
        else
            moveToWorkspace A:Web
            moveToWorkspace C:Term
            if [[ "$(workspacemonitor $WORKSPACE3)" == $ACTIVEMONITOR ]]; then
                break
            else
                moveToWorkspace A:Web
                moveToWorkspace D:Book
                if [[ "$(workspacemonitor $WORKSPACE4)" == $ACTIVEMONITOR ]]; then
                    break
                else
                    moveToWorkspace A:Web
                    moveToWorkspace E:Multimedia
                    if [[ "$(workspacemonitor $WORKSPACE5)" == $ACTIVEMONITOR ]]; then
                        break
                    else
                        moveToWorkspace A:Web
                        moveToWorkspace F:System
                        if [[ "$(workspacemonitor $WORKSPACE8)" == $ACTIVEMONITOR ]]; then
                            break
                        else
                            moveToWorkspace A:Web
                            moveToWorkspace G:Office
                            if [[ "$(workspacemonitor $WORKSPACE9)" == $ACTIVEMONITOR ]]; then
                                break
                            else
                                moveToWorkspace A:Web
                                moveToWorkspace H:Other
                                if [[ "$(workspacemonitor $WORKSPACE0)" == $ACTIVEMONITOR ]]; then
                                    break
                                else
                                    moveToWorkspace A:Web
                                fi
                            fi
                        fi
                    fi
                fi
            fi
        fi
    elif [[ $ACTIVEWORKSPACE == $WORKSPACE2 ]]; then
        moveToWorkspace C:Term
        if [[ "$(workspacemonitor $WORKSPACE3)" == $ACTIVEMONITOR ]]; then
            break
        else
            moveToWorkspace B:Editor
            moveToWorkspace D:Book
            if [[ "$(workspacemonitor $WORKSPACE4)" == $ACTIVEMONITOR ]]; then
                break
            else
                moveToWorkspace B:Editor
                moveToWorkspace E:Multimedia
                if [[ "$(workspacemonitor $WORKSPACE5)" == $ACTIVEMONITOR ]]; then
                    break
                else
                    moveToWorkspace B:Editor
                    moveToWorkspace F:System
                    if [[ "$(workspacemonitor $WORKSPACE8)" == $ACTIVEMONITOR ]]; then
                        break
                    else
                        moveToWorkspace B:Editor
                        moveToWorkspace G:Office
                        if [[ "$(workspacemonitor $WORKSPACE9)" == $ACTIVEMONITOR ]]; then
                            break
                        else
                            moveToWorkspace B:Editor
                            moveToWorkspace H:Other
                            if [[ "$(workspacemonitor $WORKSPACE0)" == $ACTIVEMONITOR ]]; then
                                break
                            else
                                moveToWorkspace B:Editor
                                moveToWorkspace A:Web
                                if [[ "$(workspacemonitor $WORKSPACE1)" == $ACTIVEMONITOR ]]; then
                                    break
                                else
                                    moveToWorkspace B:Editor
                                fi
                            fi
                        fi
                    fi
                fi
            fi
        fi
    elif [[ $ACTIVEWORKSPACE == $WORKSPACE3 ]]; then
        moveToWorkspace D:Book
        if [[ "$(workspacemonitor $WORKSPACE4)" == $ACTIVEMONITOR ]]; then
            break
        else
            moveToWorkspace C:Term
            moveToWorkspace E:Multimedia
            if [[ "$(workspacemonitor $WORKSPACE5)" == $ACTIVEMONITOR ]]; then
                break
            else
                moveToWorkspace C:Term
                moveToWorkspace F:System
                if [[ "$(workspacemonitor $WORKSPACE8)" == $ACTIVEMONITOR ]]; then
                    break
                else
                    moveToWorkspace C:Term
                    moveToWorkspace G:Office
                    if [[ "$(workspacemonitor $WORKSPACE9)" == $ACTIVEMONITOR ]]; then
                        break
                    else
                        moveToWorkspace C:Term
                        moveToWorkspace H:Other
                        if [[ "$(workspacemonitor $WORKSPACE0)" == $ACTIVEMONITOR ]]; then
                            break
                        else
                            moveToWorkspace C:Term
                            moveToWorkspace A:Web
                            if [[ "$(workspacemonitor $WORKSPACE1)" == $ACTIVEMONITOR ]]; then
                                break
                            else
                                moveToWorkspace C:Term
                                moveToWorkspace B:Editor
                                if [[ "$(workspacemonitor $WORKSPACE2)" == $ACTIVEMONITOR ]]; then
                                    break
                                else
                                    moveToWorkspace C:Term
                                fi
                            fi
                        fi
                    fi
                fi
            fi
        fi
    elif [[ $ACTIVEWORKSPACE == $WORKSPACE4 ]]; then
        moveToWorkspace E:Multimedia
        if [[ "$(workspacemonitor $WORKSPACE5)" == $ACTIVEMONITOR ]]; then
            break
        else
            moveToWorkspace D:Book
            moveToWorkspace F:System
            if [[ "$(workspacemonitor $WORKSPACE8)" == $ACTIVEMONITOR ]]; then
                break
            else
                moveToWorkspace D:Book
                moveToWorkspace G:Office
                if [[ "$(workspacemonitor $WORKSPACE9)" == $ACTIVEMONITOR ]]; then
                    break
                else
                    moveToWorkspace D:Book
                    moveToWorkspace H:Other
                    if [[ "$(workspacemonitor $WORKSPACE0)" == $ACTIVEMONITOR ]]; then
                        break
                    else
                        moveToWorkspace D:Book
                        moveToWorkspace A:Web
                        if [[ "$(workspacemonitor $WORKSPACE1)" == $ACTIVEMONITOR ]]; then
                            break
                        else
                            moveToWorkspace D:Book
                            moveToWorkspace B:Editor
                            if [[ "$(workspacemonitor $WORKSPACE2)" == $ACTIVEMONITOR ]]; then
                                break
                            else
                                moveToWorkspace D:Book
                                moveToWorkspace C:Term
                                if [[ "$(workspacemonitor $WORKSPACE3)" == $ACTIVEMONITOR ]]; then
                                    break
                                else
                                    moveToWorkspace D:Book
                                fi
                            fi
                        fi
                    fi
                fi
            fi
        fi
    elif [[ $ACTIVEWORKSPACE == $WORKSPACE5 ]]; then
        moveToWorkspace F:System
        if [[ "$(workspacemonitor $WORKSPACE8)" == "$ACTIVEMONITOR" ]]; then
            break
        else
            moveToWorkspace E:Multimedia
            moveToWorkspace G:Office
            if [[ "$(workspacemonitor $WORKSPACE9)" == "$ACTIVEMONITOR" ]]; then
                break
            else
                moveToWorkspace E:Multimedia
                moveToWorkspace H:Other
                if [[ "$(workspacemonitor $WORKSPACE0)" == "$ACTIVEMONITOR" ]]; then
                    break
                else
                    moveToWorkspace E:Multimedia
                    moveToWorkspace A:Web
                    if [[ "$(workspacemonitor $WORKSPACE1)" == "$ACTIVEMONITOR" ]]; then
                        break
                    else
                        moveToWorkspace E:Multimedia
                        moveToWorkspace B:Editor
                        if [[ "$(workspacemonitor $WORKSPACE2)" == "$ACTIVEMONITOR" ]]; then
                            break
                        else
                            moveToWorkspace E:Multimedia
                            moveToWorkspace C:Term
                            if [[ "$(workspacemonitor $WORKSPACE3)" == "$ACTIVEMONITOR" ]]; then
                                break
                            else
                                moveToWorkspace E:Multimedia
                                moveToWorkspace D:Book
                                if [[ "$(workspacemonitor $WORKSPACE4)" == "$ACTIVEMONITOR" ]]; then
                                    break
                                else
                                    moveToWorkspace E:Multimedia
                                fi
                            fi
                        fi
                    fi
                fi
            fi
        fi

    elif [[ $ACTIVEWORKSPACE == $WORKSPACE8 ]]; then
        moveToWorkspace G:Office
        if [[ "$(workspacemonitor $WORKSPACE9)" == "$ACTIVEMONITOR" ]]; then
            break
        elif [[ "$(workspacemonitor $WORKSPACE9)" == "$ACTIVEMONITOR" ]]; then
            moveToWorkspace F:System
            moveToWorkspace H:Other
            if [[ "$(workspacemonitor $WORKSPACE0)" == "$ACTIVEMONITOR" ]]; then
                break
            else
                moveToWorkspace F:System
                moveToWorkspace A:Web
                if [[ "$(workspacemonitor $WORKSPACE1)" == "$ACTIVEMONITOR" ]]; then
                    break
                else
                    moveToWorkspace F:System
                    moveToWorkspace B:Editor
                    if [[ "$(workspacemonitor $WORKSPACE2)" == "$ACTIVEMONITOR" ]]; then
                        break
                    else
                        moveToWorkspace F:System
                        moveToWorkspace C:Term
                        if [[ "$(workspacemonitor $WORKSPACE3)" == "$ACTIVEMONITOR" ]]; then
                            break
                        else
                            moveToWorkspace F:System
                            moveToWorkspace D:Book
                            if [[ "$(workspacemonitor $WORKSPACE4)" == "$ACTIVEMONITOR" ]]; then
                                break
                            else
                                moveToWorkspace F:System
                                moveToWorkspace E:Multimedia
                                if [[ "$(workspacemonitor $WORKSPACE5)" == "$ACTIVEMONITOR" ]]; then
                                    break
                                else
                                    moveToWorkspace F:System
                                fi
                            fi
                        fi
                    fi
                fi
            fi
        fi
    elif [[ $ACTIVEWORKSPACE == $WORKSPACE9 ]]; then
        moveToWorkspace H:Other
        if [[ "$(workspacemonitor $WORKSPACE0)" == "$ACTIVEMONITOR" ]]; then
            break
        else
            moveToWorkspace G:Office
            moveToWorkspace A:Web
            if [[ "$(workspacemonitor $WORKSPACE1)" == "$ACTIVEMONITOR" ]]; then
                break
            else
                moveToWorkspace G:Office
                moveToWorkspace B:Editor
                if [[ "$(workspacemonitor $WORKSPACE2)" == "$ACTIVEMONITOR" ]]; then
                    break
                else
                    moveToWorkspace G:Office
                    moveToWorkspace C:Term
                    if [[ "$(workspacemonitor $WORKSPACE3)" == "$ACTIVEMONITOR" ]]; then
                        break
                    else
                        moveToWorkspace G:Office
                        moveToWorkspace D:Book
                        if [[ "$(workspacemonitor $WORKSPACE4)" == "$ACTIVEMONITOR" ]]; then
                            break
                        else
                            moveToWorkspace G:Office
                            moveToWorkspace E:Multimedia
                            if [[ "$(workspacemonitor $WORKSPACE5)" == "$ACTIVEMONITOR" ]]; then
                                break
                            else
                                moveToWorkspace G:Office
                                moveToWorkspace F:System
                                if [[ "$(workspacemonitor $WORKSPACE8)" == "$ACTIVEMONITOR" ]]; then
                                    break
                                else
                                    moveToWorkspace G:Office
                                fi
                            fi
                        fi
                    fi
                fi
            fi
        fi
    elif [[ $ACTIVEWORKSPACE == $WORKSPACE0 ]]; then
        moveToWorkspace A:Web
        if [[ "$(workspacemonitor $WORKSPACE1)" == "$ACTIVEMONITOR" ]]; then
            break
        else
            moveToWorkspace H:Other
            moveToWorkspace B:Editor
            if [[ "$(workspacemonitor $WORKSPACE2)" == "$ACTIVEMONITOR" ]]; then
                break
            else
                moveToWorkspace H:Other
                moveToWorkspace C:Term
                if [[ "$(workspacemonitor $WORKSPACE3)" == "$ACTIVEMONITOR" ]]; then
                    break
                else
                    moveToWorkspace H:Other
                    moveToWorkspace D:Book
                    if [[ "$(workspacemonitor $WORKSPACE4)" == "$ACTIVEMONITOR" ]]; then
                        break
                    else
                        moveToWorkspace H:Other
                        moveToWorkspace E:Multimedia
                        if [[ "$(workspacemonitor $WORKSPACE5)" == "$ACTIVEMONITOR" ]]; then
                            break
                        else
                            moveToWorkspace H:Other
                            moveToWorkspace F:System
                            if [[ "$(workspacemonitor $WORKSPACE8)" == "$ACTIVEMONITOR" ]]; then
                                break
                            else
                                moveToWorkspace H:Other
                                moveToWorkspace G:Office
                                if [[ "$(workspacemonitor $WORKSPACE9)" == "$ACTIVEMONITOR" ]]; then
                                    break
                                else
                                    moveToWorkspace H:Other
                                fi
                            fi
                        fi
                    fi
                fi
            fi
        fi
    fi
}

moveworkspace_down() {
    if [[ $ACTIVEWORKSPACE == $WORKSPACE0 ]]; then
        moveToWorkspace G:Office
        if [[ "$(workspacemonitor $WORKSPACE9)" == "$ACTIVEMONITOR" ]]; then
            break
        else
            moveToWorkspace H:Other
            moveToWorkspace F:System
            if [[ "$(workspacemonitor $WORKSPACE8)" == "$ACTIVEMONITOR" ]]; then
                break
            else
                moveToWorkspace H:Other
                moveToWorkspace E:Multimedia
                if [[ "$(workspacemonitor $WORKSPACE5)" == "$ACTIVEMONITOR" ]]; then
                    break
                else
                    moveToWorkspace H:Other
                    moveToWorkspace D:Book
                    if [[ "$(workspacemonitor $WORKSPACE4)" == "$ACTIVEMONITOR" ]]; then
                        break
                    else
                        moveToWorkspace H:Other
                        moveToWorkspace C:Term
                        if [[ "$(workspacemonitor $WORKSPACE3)" == "$ACTIVEMONITOR" ]]; then
                            break
                        else
                            moveToWorkspace H:Other
                            moveToWorkspace B:Editor
                            if [[ "$(workspacemonitor $WORKSPACE2)" == "$ACTIVEMONITOR" ]]; then
                                break
                            else
                                moveToWorkspace H:Other
                                moveToWorkspace A:Web
                                if [[ "$(workspacemonitor $WORKSPACE1)" == "$ACTIVEMONITOR" ]]; then
                                    break
                                else
                                    moveToWorkspace H:Other
                                fi
                            fi
                        fi
                    fi
                fi
            fi
        fi
    elif [[ $ACTIVEWORKSPACE == $WORKSPACE9 ]]; then
        moveToWorkspace F:System
        if [[ "$(workspacemonitor $WORKSPACE8)" == "$ACTIVEMONITOR" ]]; then
            break
        else
            moveToWorkspace G:Office
            moveToWorkspace E:Multimedia
            if [[ "$(workspacemonitor $WORKSPACE5)" == "$ACTIVEMONITOR" ]]; then
                break
            else
                moveToWorkspace G:Office
                moveToWorkspace D:Book
                if [[ "$(workspacemonitor $WORKSPACE4)" == "$ACTIVEMONITOR" ]]; then
                    break
                else
                    moveToWorkspace G:Office
                    moveToWorkspace C:Term
                    if [[ "$(workspacemonitor $WORKSPACE3)" == "$ACTIVEMONITOR" ]]; then
                        break
                    else
                        moveToWorkspace G:Office
                        moveToWorkspace B:Editor
                        if [[ "$(workspacemonitor $WORKSPACE2)" == "$ACTIVEMONITOR" ]]; then
                            break
                        else
                            moveToWorkspace G:Office
                            moveToWorkspace A:Web
                            if [[ "$(workspacemonitor $WORKSPACE1)" == "$ACTIVEMONITOR" ]]; then
                                break
                            else
                                moveToWorkspace G:Office
                                moveToWorkspace H:Other
                                if [[ "$(workspacemonitor $WORKSPACE0)" == "$ACTIVEMONITOR" ]]; then
                                    break
                                else
                                    moveToWorkspace G:Office
                                fi
                            fi
                        fi
                    fi
                fi
            fi
        fi
    elif [[ $ACTIVEWORKSPACE == $WORKSPACE8 ]]; then
        moveToWorkspace E:Multimedia
        if [[ "$(workspacemonitor $WORKSPACE5)" == "$ACTIVEMONITOR" ]]; then
            break
        else
            moveToWorkspace F:System
            moveToWorkspace D:Book
            if [[ "$(workspacemonitor $WORKSPACE4)" == "$ACTIVEMONITOR" ]]; then
                break
            else
                moveToWorkspace F:System
                moveToWorkspace C:Term
                if [[ "$(workspacemonitor $WORKSPACE3)" == "$ACTIVEMONITOR" ]]; then
                    break
                else
                    moveToWorkspace F:System
                    moveToWorkspace B:Editor
                    if [[ "$(workspacemonitor $WORKSPACE2)" == "$ACTIVEMONITOR" ]]; then
                        break
                    else
                        moveToWorkspace F:System
                        moveToWorkspace A:Web
                        if [[ "$(workspacemonitor $WORKSPACE1)" == "$ACTIVEMONITOR" ]]; then
                            break
                        else
                            moveToWorkspace F:System
                            moveToWorkspace H:Other
                            if [[ "$(workspacemonitor $WORKSPACE0)" == "$ACTIVEMONITOR" ]]; then
                                break
                            else
                                moveToWorkspace F:System
                                moveToWorkspace G:Office
                                if [[ "$(workspacemonitor $WORKSPACE9)" == "$ACTIVEMONITOR" ]]; then
                                    break
                                else
                                    moveToWorkspace F:System
                                fi
                            fi
                        fi
                    fi
                fi
            fi
        fi
    elif [[ $ACTIVEWORKSPACE == $WORKSPACE5 ]]; then
        moveToWorkspace D:Book
        if [[ "$(workspacemonitor $WORKSPACE4)" == "$ACTIVEMONITOR" ]]; then
            break
        else
            moveToWorkspace E:Multimedia
            moveToWorkspace C:Term
            if [[ "$(workspacemonitor $WORKSPACE3)" == "$ACTIVEMONITOR" ]]; then
                break
            else
                moveToWorkspace E:Multimedia
                moveToWorkspace B:Editor
                if [[ "$(workspacemonitor $WORKSPACE2)" == "$ACTIVEMONITOR" ]]; then
                    break
                else
                    moveToWorkspace E:Multimedia
                    moveToWorkspace A:Web
                    if [[ "$(workspacemonitor $WORKSPACE1)" == "$ACTIVEMONITOR" ]]; then
                        break
                    else
                        moveToWorkspace E:Multimedia
                        moveToWorkspace H:Other
                        if [[ "$(workspacemonitor $WORKSPACE0)" == "$ACTIVEMONITOR" ]]; then
                            break
                        else
                            moveToWorkspace E:Multimedia
                            moveToWorkspace G:Office
                            if [[ "$(workspacemonitor $WORKSPACE9)" == "$ACTIVEMONITOR" ]]; then
                                break
                            else
                                moveToWorkspace E:Multimedia
                                moveToWorkspace F:System
                                if [[ "$(workspacemonitor $WORKSPACE8)" == "$ACTIVEMONITOR" ]]; then
                                    break
                                else
                                    moveToWorkspace E:Multimedia
                                fi
                            fi
                        fi
                    fi
                fi
            fi
        fi
    elif [[ $ACTIVEWORKSPACE == $WORKSPACE4 ]]; then
        moveToWorkspace C:Term
        if [[ "$(workspacemonitor $WORKSPACE3)" == "$ACTIVEMONITOR" ]]; then
            break
        else
            moveToWorkspace D:Book
            moveToWorkspace B:Editor
            if [[ "$(workspacemonitor $WORKSPACE2)" == "$ACTIVEMONITOR" ]]; then
                break
            else
                moveToWorkspace D:Book
                moveToWorkspace A:Web
                if [[ "$(workspacemonitor $WORKSPACE1)" == "$ACTIVEMONITOR" ]]; then
                    break
                else
                    moveToWorkspace D:Book
                    moveToWorkspace H:Other
                    if [[ "$(workspacemonitor $WORKSPACE0)" == "$ACTIVEMONITOR" ]]; then
                        break
                    else
                        moveToWorkspace D:Book
                        moveToWorkspace G:Office
                        if [[ "$(workspacemonitor $WORKSPACE9)" == "$ACTIVEMONITOR" ]]; then
                            break
                        else
                            moveToWorkspace D:Book
                            moveToWorkspace F:System
                            if [[ "$(workspacemonitor $WORKSPACE8)" == "$ACTIVEMONITOR" ]]; then
                                break
                            else
                                moveToWorkspace D:Book
                                moveToWorkspace E:Multimedia
                                if [[ "$(workspacemonitor $WORKSPACE5)" == "$ACTIVEMONITOR" ]]; then
                                    break
                                else
                                    moveToWorkspace D:Book
                                fi
                            fi
                        fi
                    fi
                fi
            fi
        fi
    elif [[ $ACTIVEWORKSPACE == $WORKSPACE3 ]]; then
        moveToWorkspace B:Editor
        if [[ "$(workspacemonitor $WORKSPACE2)" == "$ACTIVEMONITOR" ]]; then
            break
        else
            moveToWorkspace C:Term
            moveToWorkspace A:Web
            if [[ "$(workspacemonitor $WORKSPACE1)" == "$ACTIVEMONITOR" ]]; then
                break
            else
                moveToWorkspace C:Term
                moveToWorkspace H:Other
                if [[ "$(workspacemonitor $WORKSPACE0)" == "$ACTIVEMONITOR" ]]; then
                    break
                else
                    moveToWorkspace C:Term
                    moveToWorkspace G:Office
                    if [[ "$(workspacemonitor $WORKSPACE9)" == "$ACTIVEMONITOR" ]]; then
                        break
                    else
                        moveToWorkspace C:Term
                        moveToWorkspace F:System
                        if [[ "$(workspacemonitor $WORKSPACE8)" == "$ACTIVEMONITOR" ]]; then
                            break
                        else
                            moveToWorkspace C:Term
                            moveToWorkspace E:Multimedia
                            if [[ "$(workspacemonitor $WORKSPACE5)" == "$ACTIVEMONITOR" ]]; then
                                break
                            else
                                moveToWorkspace C:Term
                                moveToWorkspace D:Book
                                if [[ "$(workspacemonitor $WORKSPACE4)" == "$ACTIVEMONITOR" ]]; then
                                    break
                                else
                                    moveToWorkspace C:Term
                                fi
                            fi
                        fi
                    fi
                fi
            fi
        fi
    elif [[ $ACTIVEWORKSPACE == $WORKSPACE2 ]]; then
        moveToWorkspace A:Web
        if [[ "$(workspacemonitor $WORKSPACE1)" == "$ACTIVEMONITOR" ]]; then
            break
        else
            moveToWorkspace B:Editor
            moveToWorkspace H:Other
            if [[ "$(workspacemonitor $WORKSPACE0)" == "$ACTIVEMONITOR" ]]; then
                break
            else
                moveToWorkspace B:Editor
                moveToWorkspace G:Office
                if [[ "$(workspacemonitor $WORKSPACE9)" == "$ACTIVEMONITOR" ]]; then
                    break
                else
                    moveToWorkspace B:Editor
                    moveToWorkspace F:System
                    if [[ "$(workspacemonitor $WORKSPACE8)" == "$ACTIVEMONITOR" ]]; then
                        break
                    else
                        moveToWorkspace B:Editor
                        moveToWorkspace E:Multimedia
                        if [[ "$(workspacemonitor $WORKSPACE5)" == "$ACTIVEMONITOR" ]]; then
                            break
                        else
                            moveToWorkspace B:Editor
                            moveToWorkspace D:Book
                            if [[ "$(workspacemonitor $WORKSPACE4)" == "$ACTIVEMONITOR" ]]; then
                                break
                            else
                                moveToWorkspace B:Editor
                                moveToWorkspace C:Term
                                if [[ "$(workspacemonitor $WORKSPACE3)" == "$ACTIVEMONITOR" ]]; then
                                    break
                                else
                                    moveToWorkspace B:Editor
                                fi
                            fi
                        fi
                    fi
                fi
            fi
        fi
    elif [[ $ACTIVEWORKSPACE == $WORKSPACE1 ]]; then
        moveToWorkspace H:Other
        if [[ "$(workspacemonitor $WORKSPACE0)" == "$ACTIVEMONITOR" ]]; then
            break
        else
            moveToWorkspace A:Web
            moveToWorkspace G:Office
            if [[ "$(workspacemonitor $WORKSPACE9)" == "$ACTIVEMONITOR" ]]; then
                break
            else
                moveToWorkspace A:Web
                moveToWorkspace F:System
                if [[ "$(workspacemonitor $WORKSPACE8)" == "$ACTIVEMONITOR" ]]; then
                    break
                else
                    moveToWorkspace A:Web
                    moveToWorkspace E:Multimedia
                    if [[ "$(workspacemonitor $WORKSPACE5)" == "$ACTIVEMONITOR" ]]; then
                        break
                    else
                        moveToWorkspace A:Web
                        moveToWorkspace D:Book
                        if [[ "$(workspacemonitor $WORKSPACE4)" == "$ACTIVEMONITOR" ]]; then
                            break
                        else
                            moveToWorkspace A:Web
                            moveToWorkspace C:Term
                            if [[ "$(workspacemonitor $WORKSPACE3)" == "$ACTIVEMONITOR" ]]; then
                                break
                            else
                                moveToWorkspace A:Web
                                moveToWorkspace  B:Editor
                                if [[ "$(workspacemonitor $WORKSPACE2)" == "$ACTIVEMONITOR" ]]; then
                                    break
                                else
                                    moveToWorkspace  A:Web
                                fi
                            fi
                        fi
                    fi
                fi
            fi
        fi
    fi
}

case "$1" in
up)
    moveworkspace_up
    ;;
down)
    moveworkspace_down
    ;;
esac
