#!/bin/sh

hypr=$HOME/.config/hypr
wallpaper_folder=$hypr/themes/one/wallpapers_evil

wallpaper_location="$(ls $wallpaper_folder | rofi -dmenu -theme ~/.config/rofi/themes/easy/rofi/launcher.rasi)"


$hypr/scripts/variables/set_env background "$wallpaper_folder/$wallpaper_location"

$hypr/themes/one/scripts/wallpaper

# echo "~/.config/hypr/themes/one/wallpapers$wallpaper"
# swaybg -m fill -i "$HOME/.config/hypr/themes/one/wallpapers/$wallpaper" &
