#!/bin/sh

source $HOME/.config/hypr/scripts/variables/wall_directory

wallpaper_folder=$WALL_DIRECTORY

wallpaper_location="$(ls $wallpaper_folder | rofi -dmenu -theme ~/.config/rofi/themes/easy/rofi/launcher.rasi)"


$hypr/scripts/variables/set_env background "$wallpaper_folder/$wallpaper_location"

$hypr/dots/eww/themes/one/scripts/wallpaper

# echo "~/.config/hypr/dots/eww/themes/one/wallpapers$wallpaper"
# swaybg -m fill -i "$HOME/.config/hypr/dots/eww/themes/one/wallpapers/$wallpaper" &
