# Environment variables

env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland
env = WLR_NO_HARDWARE_CURSORS, 1
env = WINE_VK_VULKAN_ONLY, 1
env = GKT_THEME, Everforest-Dark-BL
# FCITX
env = XMODIFIERS, fcitx5
env = GTK_IM_MODULE, fcitx5
env = QT_IM_MODULE, fcitx5

env = XCURSOR_THEME, breeze_cursors # Cursors
env = XCURSOR_SIZE, 24 # Cursors size
env = EDITOR, nvim

env = GTK_USE_PORTAL, 1 # Helps to use dolphin file-picker in most apps by default
# env = QT_STYLE_OVERRIDE, kvantum # Still used to theme apps like VLC, etc
env = QT_QPA_PLATFORMTHEME, qt6ct
env = FZF_DEFAULT_OPTS, --bind alt-j:down,alt-k:up,ctrl-u:preview-up,ctrl-d:preview-down
env = HYPRSHOT_DIR, $HOME/Pictures/Screenshots/ # Hyprshot needed variable to set default screenshot directory
env = _JAVA_OPTIONS, '-Dawt.useSystemAAFontSettings=gasp' # Fix ugly fonts in JAVA applications

# Force all Apps to use Wayland
env = GDK_BACKEND,wayland,x11,*
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_STYLE_OVERRIDE,kvantum
env = MOZ_ENABLE_WAYLAND,1
env = ELECTRON_OZONE_PLATFORM_HINT,wayland
env = OZONE_PLATFORM,wayland
env = XDG_SESSION_TYPE,wayland

xwayland {
  force_zero_scaling = true
}

# Don't show update on first launch
ecosystem {
  no_update_news = true
}
