[ids]

*

[main]

# Maps capslock to escape when pressed and control when held.
# capslock = overload(control, esc)

# Remaps the escape key to capslock
# rightmeta = rightshift
# compose = rightshift

# Spanish Keyboard missing <> key with fkeys having a weird behaviour
# brightnessdown = <
brightnessdown = f1
brightnessup = f2
scale = f3
dashboard = f4
kbdillumdown = f5
kbdillumup = f6
previoussong = f7
playpause = f8
nextsong = f9
mute = f10
volumedown = f11
volumenup = f12

# brightnessdown = <

# Maps capslock to capslock when pressed and 'remapping' layer when held
# capslock = overload(remapping, capslock)
compose = overload(alt, compose)

[shift]
# brightnessdown = >


# [remapping]
# tab =tab
# j = left
# k = down
# l = right
# i = up
# u = home
# o = end
# y = pageup
# h = pagedown
# p = delete
# ; = insert
# [ = esc
# ] = tab
# 2 = 1
# 3 = !
# d = ~
