# Autostart applications

# exec = $scripts/utils/wallpaper/wallpaper # old script (sww)
exec-once = $scripts/utils/dynamic-wallpaper.sh > /tmp/dynamic-wallpaper.log 2>&1
# exec-once = $scripts/utils/wallpaper/wallpaper-random -i 900 # Auto Wallpaper Update every 15m
# exec-once = $scripts/utils/wallpaper/random_wall start
# exec = pcmanfm-qt --desktop & # Set Wallpaper with icons on screen using pcmanfm-qt

# exec-once = swaync # Launch swaync
exec-once = hyprpm reload -n # Reload hyprland plugins
exec-once = fcitx5 --replace -d # Launch fcitx5

# Core components (authentication, lock screen, notification daemon)
exec-once = dbus-update-activation-environment --all
exec-once = gnome-keyring-daemon --start --components=secrets
# exec-once = /usr/lib/polkit-kde-authentication-agent-1 &
exec-once = kwalletd6
exec-once = $scripts/utils/notifyBatteryStatus & # Launch script to detect battery status
exec-once = hypridle # detect idle time and lock screen
# exec-once = sway-audio-idle-inhibit # Don't sleep while something is playing.
exec-once = wl-clip-persist --clipboard regular # Clipboard history
exec-once = wl-paste --watch cliphist store # Clipboard history
exec-once = clipse -listen   # Record clipboard history
exec-once = sleep 1 && dbus-update-activation-environment --all # Set environment variables
exec-once = input-remapper-control --command autoload & # command to remap keys

# Launch apps
exec-once = $personalFiles/automation/autostart # Launch auto-start apps (OneMonitor)
# exec-once = telegram-desktop -startintray
# exec-once = mailspring --background &
# exec-once = /usr/lib/kdeconnectd -platform offscreen &

# Set GTK theme
exec-once = gsettings set org.gnome.desktop.interface cursor-theme "breeze_cursors"
exec-once = gsettings set org.gnome.desktop.interface cursor-size "24"
exec-once = gsettings set org.gnome.desktop.interface font-name 'Lexend Deca Regular 10'

exec-once = gsettings set org.gnome.desktop.interface gtk-theme "Material-Red-Dark"
exec-once = gsettings set org.gnome.desktop.interface icon-theme "SeviDDE-red-dark"
exec-once = (waybar &) && sleep 1 && pkill waybar && waybar & # without this pipewire module woudn't load normally ¿?
# exec-once = qs # theme-time-daemon won't reload theme script at start if the time of the day doesn't need it (so start qs manually)
exec-once = sleep 3 && $hyprScripts/theme-time-daemon.sh
exec-once = tmux new -Ads main # Start tmux
