#!/bin/sh

source $HOME/.config/hypr/scripts/variables/wall_directory

wallpaper_folder=$WALL_DIRECTORY

# bemenu theming
. $HOME/.local/bin/bemenu-theming

wallpaper_location="$(ls $wallpaper_folder | rofi -dmenu -p "Select a wallpaper")"


$hypr/scripts/variables/set_env background "$wallpaper_folder/$wallpaper_location"

$hypr/scripts/wallpaper
