#!/bin/bash

# Will start bluemail and kill its window only once it's loaded (like a background process since it can't by itself)
# Will also move the focus to the HDMI-A-1 monitor

hyprctl dispatch focusmonitor HDMI-A-1
(bluemail &) && sleep 5
hyprctl dispatch movetoworkspace name:A:Web
hyprctl dispatch movecursortocorner 2
sleep 2 && hyprctl dispatch killactive && sleep 1
if [ $? -eq 0 ]; then

    # then Start dolphin in a predefined position and reposition the mouse cursor to the right top corner
    # (dolphin &) && sleep 3 && hyprctl dispatch movecursortocorner 2 && hyprctl dispatch movetoworkspace name:D:Book
    megasync &
    sleep 3
    hyprctl dispatch focusmonitor HDMI-A-1
else
    notify-send "something went wrong"
fi
