#!/bin/bash

export BEMENU_OPTS="
  --tb '#AFAFAF'\
  --tf '#151515'\
  --fb '#151515'\
  --ff '#E1E1E1'\
  --nb '#1d1f21'\
  --nf '#E1E1E1'\
  --hb '#151515'\
  --hf '#9998a8'\
  --nf '#E1E1E1'\
  --af '#E1E1E1'\
  --ab '#151515'\ 
  -H 32\ 
  -m 500\
  --fn 'SF Pro Rounded Regular 11'\
  --hp 8\
  --ch 16\
  --cw 2|
"
