#!/bin/bash

focus_mode() {
    hyprctl dispatch fullscreen 0
    hyprctl dispatch fullscreen 0

    # sleep 1
    hyprctl keyword general:border_size 1
    hyprctl keyword general:gaps_in 0
    hyprctl keyword general:gaps_out 0
}
not_focus_mode() {
    hyprctl dispatch fullscreen 0 #bcz Hyprland cannot update the size of the screen automatically
    hyprctl dispatch fullscreen 0
    # sleep 1

    hyprctl keyword general:border_size 1
    hyprctl keyword general:gaps_in 5
    hyprctl keyword general:gaps_out 10
    hyprctl keyword decoration:rounding 9
}
without_waybar() {
    hyprctl dispatch fullscreen 0
    hyprctl dispatch fullscreen 0

    # sleep 1
    hyprctl keyword general:border_size 1
    hyprctl keyword general:gaps_in 0
    hyprctl keyword general:gaps_out 0
    pkill waybar &
}

case "$1" in
focus) focus_mode ;;
notfocus) not_focus_mode ;;
nowaybar) without_waybar ;;
esac
