#!/bin/bash

file=~/.config/ags/main.ts
file2=~/.config/ags/options.ts
line='// ...forMonitors(Bar),'
line2='spacing: opt(6),'

if grep -q "$line" "$file"; then
    # Line is present, uncomment it
    sed -i "s|$line|...forMonitors(Bar),|" "$file"
    echo "Line uncommented."
    ags -q
    ags &> /dev/null &
    hyprctl dispatch fullscreen 0 #bcz Hyprland cannot update the size of the screen automatically
    # sleep 1
    hyprctl dispatch fullscreen 0
    hyprctl keyword decoration:drop_shadow 1 # enable shadows on Hyprland
elif [ $? -eq 1 ]; then
    # Line is present, comment it
    # sed -i "s|...forMonitors(Bar),|$line|" "$file" # Uncomment this line if you want to disable ags Bar
    echo "Line commented."
    ags -q
    ags &> /dev/null &
    hyprctl dispatch fullscreen 0
    hyprctl dispatch fullscreen 0

    sleep 2
  hyprctl keyword general:border_size 2
  hyprctl keyword general:gaps_in 1
  hyprctl keyword general:gaps_out 3
  hyprctl keyword decoration:rounding 0
  hyprctl keyword decoration:drop_shadow 0 # Disable shadows on Hyprland
else
    echo "An error occurred while running grep."
fi
