#!/bin/bash

# foot --title=Fella -D "${HOME}/Sync" zellij -s HOME -l ~/.config/zellij/kellig_layouts/yazi-zellij.kdl
kitty --title=Fella -d "${HOME}/Sync" zellij -s HOME -l ~/.config/zellij/kellig_layouts/yazi-zellij.kdl 
