#!/bin/bash

# Variable of Wallpapers Directory
hypr=$HOME/.config/hypr
wallpaper_folder=$hypr/themes/one/wallpapers

# Go to Wallpaper Directory
cd $wallpaper_folder

# Create a variable to store the output.
randomImage=""

# Run the command.
randomImage=$(shuf -n 1 -e *.jpg *.png *.jpeg)

$hypr/scripts/variables/set_env background "$wallpaper_folder/$randomImage"

# Change wallpaper
swww img $randomImage
# swww img -t any --transition-bezier 0.0,0.0,1.0,1.0 --transition-duration .8 --transition-step 255 --transition-fps 60 $randomImage
