#!/bin/bash

if pgrep -x "waybar" > /dev/null; then
    ~/.config/hypr/dots/.scripts/focus_mode notfocus && killall waybar && waybar &
else
    ~/.config/hypr/dots/.scripts/focus_mode notfocus && waybar & 
fi
