#!/bin/bash

DIR="$HOME/.config/"
RASI="$DIR/rofi/config.rasi"

files=$(fd)
history=$(cat ~/.files_history)
history_file="$HOME/.files_history"

title="rofi-finder"
rofi_command="rofi -dmenu -theme $RASI -i -p $title"
rofi_input=$(printf "%s\n" "${history[@]}" "${files[@]}")
selected_file=$(echo -e "$rofi_input" | $rofi_command)

if [ $? -eq 0 ] && [ -n "$selected_file" ]; then
    # grep -qFx "$selected_file" ~/files.history || (echo "$selected_file"; cat ~/files.history) > ~/files.history.tmp && mv ~/files.history.tmp ~/files.history
    # Check if the selected file is already in the history file.
    if grep -qFx "$selected_file" ~/.files_history; then
        # Remove the line from the file and save the result to a temporary file
        grep -vFx "$selected_file" "$history_file" > tmpfile && mv tmpfile "$history_file"
        # Add the search line at the top of the file
        echo "$selected_file" | cat - "$history_file" > tmpfile && mv tmpfile "$history_file"
        xdg-open "$selected_file"
        exit 1
    fi
    # Add the selected file to the top of the history file.
    echo "$selected_file" > ~/.files_history.tmp
    cat ~/.files_history >> ~/.files_history.tmp
    mv ~/.files_history.tmp ~/.files_history
    xdg-open "$selected_file"
fi
