#!/bin/bash

TERM="foot -c /home/LostOnTheSeas/.config/foot/themes/dark-red.ini"
launcher="rofi"
# Dark theme
launcher_theme="spotlight-dark"
ROFI_THEMES="$HOME/.config/rofi/themes"
LAUNCH1="${ROFI_THEMES}/Go.rasi"
LAUNCH2="${ROFI_THEMES}/Ya.rasi"
LAUNCH3="${ROFI_THEMES}/Bi.rasi"
LAUNCH4="${ROFI_THEMES}/Br.rasi"

WORKSPACE1="A:Cyþan"
WORKSPACE2="B:Līþan"
WORKSPACE3="C:Wǣpn"
WORKSPACE4="D:Wæl"
WORKSPACE5="E:Ġemynd"
WORKSPACE6="F:Ġesiht"
WORKSPACE7="G:Hām"
WORKSPACE8="H:Sċēawere"
WORKSPACE9="I:Mēce"
WORKSPACE0="J:Frēoþ"

export LAUNCHER=$launcher
export LAUNCHER_THEME=$launcher_theme
