#!/bin/bash

TERM="foot -c /home/LostOnTheSeas/.config/foot/themes/dark-red.ini"
launcher="rofi"
# Dark theme
launcher_theme="spotlight-dark"
ROFI_THEMES="$HOME/.config/rofi/themes"
LAUNCH1="${ROFI_THEMES}/Go.rasi"
LAUNCH2="${ROFI_THEMES}/Ya.rasi"
LAUNCH3="${ROFI_THEMES}/Bi.rasi"
LAUNCH4="${ROFI_THEMES}/Br.rasi"

INTERNAL_MONITOR="eDP-1"
EXTERNAL_MONITOR="HDMI-A-1"

# TYPEOFWORKSPACE="workspace name:"
TYPEOFWORKSPACE="workspace"
WORKSPACE1="1"
WORKSPACE2="2"
WORKSPACE3="3"
WORKSPACE4="4"
WORKSPACE5="5"
WORKSPACE6="6"
WORKSPACE7="7"
WORKSPACE8="8"
WORKSPACE9="9"
WORKSPACE0="0"

export LAUNCHER=$launcher
export LAUNCHER_THEME=$launcher_theme
