#!/bin/bash
cd ~/yt-local
echo "Creating env"
python -m venv env
echo "Activating env"
source env/bin/activate
echo "Installing requirements"
pip3 install -r requirements.txt
echo "running program"
python server.py
