[manager]
cwd = { fg = "#e7e7e7" }

# Hovered
hovered = { fg = "#171717", bg = "#b2b5b3" }
preview_hovered = { underline = true }

# Find
find_keyword = { fg = "#F4BF75", italic = true }
find_position = { fg = "#51a4e7", bg = "reset", italic = true }

# Marker
marker_selected = { fg = "#90A959", bg = "#90A959" }
marker_copied = { fg = "#F4BF75", bg = "#F4BF75" }
marker_cut = { fg = "#b46958", bg = "#b46958" }

# Tab
tab_active = { fg = "#171717", bg = "#b2b5b3" }
tab_inactive = { fg = "#cad3f5", bg = "#313234" }
tab_width = 1

# Border
border_symbol = "│"
border_style = { fg = "#88afa2" }

# Highlighting
# syntect_theme = "~/.config/bat/themes/Catppuccin-macchiato.tmTheme"

[status]
separator_open = ""
separator_close = ""
separator_style = { fg = "#313234", bg = "#313234" }

# Mode
mode_normal = { fg = "#171717", bg = "#b2b5b3", bold = true }
mode_select = { fg = "#171717", bg = "#90A959", bold = true }
mode_unset = { fg = "#171717", bg = "#f0c6c6", bold = true }

# Progress
progress_label = { fg = "#ffffff", bold = true }
progress_normal = { fg = "#b2b5b3", bg = "#313234" }
progress_error = { fg = "#b46958", bg = "#313234" }

# Permissions
permissions_t = { fg = "#b2b5b3" }
permissions_r = { fg = "#F4BF75" }
permissions_w = { fg = "#b46958" }
permissions_x = { fg = "#90A959" }
permissions_s = { fg = "#88afa2" }

# : }}}


# : Input {{{

[input]
border = { fg = "#b2b5b3" }
title = {}
value = {}
selected = { reversed = true }

[select]
border = { fg = "#b2b5b3" }
active = { fg = "#51a4e7" }
inactive = {}

[tasks]
border = { fg = "#b2b5b3" }
title = {}
hovered = { underline = true }

[which]
mask = { bg = "#313234" }
cand = { fg = "#88afa2" }
rest = { fg = "#e7e7e7" }
desc = { fg = "#FCA57E" }
separator = "  "
separator_style = { fg = "#5b6078" }

[help]
on = { fg = "#FCA57E" }
exec = { fg = "#88afa2" }
desc = { fg = "#939ab7" }
hovered = { bg = "#5b6078", bold = true }
footer = { fg = "#494d64", bg = "#e7e7e7" }

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "#88afa2" },

	# Videos
	{ mime = "video/*", fg = "#F4BF75" },
	{ mime = "audio/*", fg = "#F4BF75" },

	# Archives
	{ mime = "application/zip", fg = "#9077e7" },
	{ mime = "application/gzip", fg = "#9077e7" },
	{ mime = "application/x-tar", fg = "#9077e7" },
	{ mime = "application/x-bzip", fg = "#9077e7" },
	{ mime = "application/x-bzip2", fg = "#9077e7" },
	{ mime = "application/x-7z-compressed", fg = "#9077e7" },
	{ mime = "application/x-rar", fg = "#9077e7" },

	# Fallback
	{ name = "*", fg = "#e7e7e7" },
	{ name = "*/", fg = "#b2b5b3" }
]

[icons]

"Desktop/"     = ""
"Documents/"   = ""
"Downloads/"   = ""
"Pictures/"    = ""
"Music/"       = ""
"Movies/"      = ""
"Videos/"      = ""
"Public/"      = ""
"Library/"     = ""
"Development/" = ""
".config/"     = ""

# Git
".git/"          = ""
".gitignore"     = ""
".gitmodules"    = ""
".gitattributes" = ""

# Dotfiles
".DS_Store"    = ""
".bashrc"      = ""
".bashprofile" = ""
".zshrc"       = ""
".zshenv"      = ""
".zprofile"    = ""
".vimrc"       = ""

# Text
"*.txt" = ""
"*.md"  = ""

# Archives
"*.zip" = ""
"*.tar" = ""
"*.gz"  = ""
"*.7z"  = ""

# Audio
"*.mp3"  = ""
"*.flac" = ""
"*.wav"  = ""

# Movies
"*.mp4" = ""
"*.mkv" = ""
"*.avi" = ""
"*.mov" = ""

# Images
"*.jpg"  = ""
"*.jpeg" = ""
"*.png"  = ""
"*.gif"  = ""
"*.webp" = ""
"*.avif" = ""
"*.bmp"  = ""
"*.ico"  = ""
"*.svg"  = ""

# Programming
"*.c"     = ""
"*.cpp"   = ""
"*.h"     = ""
"*.hpp"   = ""
"*.rs"    = ""
"*.go"    = ""
"*.py"    = ""
"*.js"    = ""
"*.ts"    = ""
"*.tsx"   = ""
"*.jsx"   = ""
"*.rb"    = ""
"*.php"   = ""
"*.java"  = ""
"*.sh"    = ""
"*.fish"  = ""
"*.swift" = ""
"*.vim"   = ""
"*.lua"   = ""
"*.html"  = ""
"*.css"   = ""
"*.scss"  = ""
"*.json"  = ""
"*.toml"  = ""
"*.yml"   = ""
"*.yaml"  = ""
"*.ini"   = ""
"*.conf"  = ""

# Default
"*"  = ""
"*/" = ""
