[manager]
layout         = [ 1, 4, 3 ]
sort_by        = "modified"
sort_sensitive = false
sort_reverse   = true
sort_dir_first = true
show_hidden    = false
show_symlink   = true

[preview]
tab_size   = 2
max_width  = 600
max_height = 900
cache_dir  = ""

[opener]
folder = [
	{ exec = 'nautilus "$@"', desc = "Nautilus" },
	{ exec = 'dolphin "$@"', desc = "Dolphin" },
	{ exec = 'neovide "$@"', desc = "Neovide" },
	{ exec = '$EDITOR "$@"', desc = "Neovim" },
]
archive = [
	{ exec = 'unrar "$1"', desc = "Extract here unrar" },
	{ exec = 'unzip "$1"', desc = "Extract here zip" },
]
text = [
	{ exec = '$EDITOR "$@"', block = true },
	{ exec = 'neovide "$@"', block = true },
	{ exec = 'code "$@"', block = true },
	{ exec = 'sh "$@"', block = true },
]
image = [
	{ exec = 'loupe "$@"', desc = "Open with Loupe" },
	{ exec = 'imv-dir "$@"', desc = "Open with img-dir" },
	{ exec = 'firefox "$@"', desc = "Open with Firefox" },
	# { exec = '''exiftool "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show EXIF" },
]
video = [
	{ exec = 'mpv "$@"', desc = "Open with MPV" },
	{ exec = 'vlc "$@"', desc = "Open with VLC" },
	# { exec = '''mediainfo "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show media info" },
]
audio = [
	{ exec = 'amberol "$@"', desc = "Open with amberol" },
	{ exec = 'mpv --no-video "$@"', desc = "Open with MPV" },
	# { exec = '''mediainfo "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show media info" },
]
fallback = [
	{ exec = 'open "$@"', desc = "Open" },
	{ exec = 'open -R "$@"', desc = "Reveal in Finder" },
	{ exec = 'wps "$@"', desc = "Open in WPS" },
]

document = [
	{ exec = 'sioyek "$@"', desc = "Open with sioyek" },
	{ exec = 'zathura "$@"', desc = "Open with Zathura" },
]

[open]
rules = [
	{ name = "*/", use = "folder" },

	{ mime = "text/*", use = "text" },
	{ mime = "image/*", use = "image" },
	{ mime = "video/*", use = "video" },
	{ mime = "audio/*", use = "audio" },
	{ mime = "inode/x-empty", use = "text" },

	{ mime = "application/json", use = "text" },
	{ mime = "*/javascript", use = "text" },

	{ mime = "application/zip", use = "archive" },
	{ mime = "application/gzip", use = "archive" },
	{ mime = "application/x-tar", use = "archive" },
	{ mime = "application/x-bzip", use = "archive" },
	{ mime = "application/x-bzip2", use = "archive" },
	{ mime = "application/x-7z-compressed", use = "archive" },
	{ mime = "application/x-rar", use = "archive" },
  
  { mime = "application/pdf", use = "document" },

	{ mime = "*", use = "fallback" },
]

[tasks]
micro_workers = 5
macro_workers = 10
bizarre_retry = 5

[log]
enabled = false
